In [19]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_pickle("../4-idr-properties/processed-data/0-s288c-step4.pkl")

In [24]:
df.columns

Index(['node', '_wkshell', 'degree_centrality', 'betweenness_centrality',
       'eigenvector_centrality', 'closeness_centrality', 'load_centrality',
       'pagerank', 'information_centrality', 'CentralityCosDist_rank',
       'CentralityCosDist_similarity_score', 'has_verified_sequence',
       'sequence', 'UniProtKB-AC', 'DeepTMHMM_trimmed_sequence',
       'DeepTMHMM_class', 'cleavage_site_start', 'signalP_trimmed_sequence',
       'ProteinName', 'GO_terms', 'GO_terms_human_readable',
       'localization_keywords', 'parsed_functions', 'parsed_PTMs',
       'ptm_bronze', 'ptm_gold', 'ptm_silver', 'IDR_count', 'IDR_sequences',
       'IDR_ranges', 'N_aa_disordered', 'disorder_fraction',
       'is_disordered_0.05', 'is_disordered_0.10', 'is_disordered_0.15',
       'is_disordered_0.20', 'is_disordered_0.25', 'is_disordered_0.30',
       'is_disordered_0.35', 'is_disordered_0.40', 'is_disordered_0.45',
       'is_disordered_0.50', 'is_disordered_0.55', 'is_disordered_0.60',
       'is_disordered_0.65', 'is_disordered_0.70', 'is_disordered_0.75',
       'is_disordered_0.80', 'is_disordered_0.85', 'is_disordered_0.90',
       'is_disordered_0.95', 'is_disordered_1.00', 'albatross', 'cider'],
      dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3927 entries, 0 to 3926
Data columns (total 54 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   node                                3927 non-null   object
 1   _wkshell                            3927 non-null   int64
 2   degree_centrality                   3927 non-null   float64
 3   betweenness_centrality              3927 non-null   float64
 4   eigenvector_centrality              3927 non-null   float64
 5   closeness_centrality                3927 non-null   float64
 6   load_centrality                     3927 non-null   float64
 7   pagerank                            3927 non-null   float64
 8   information_centrality              3927 non-null   float64
 9   CentralityCosDist_rank              3927 non-null   float64
 10  CentralityCosDist_similarity_score  3927 non-null   float64
 11  has_verified_sequence               3927 non-null   bool
 12  sequence                            3876 non-null   object
 13  UniProtKB-AC                        3885 non-null   object
 14  DeepTMHMM_trimmed_sequence          3875 non-null   object
 15  DeepTMHMM_class                     3876 non-null   object
 16  cleavage_site_start                 129 non-null    float64
 17  signalP_trimmed_sequence            3876 non-null   object
 18  ProteinName                         3885 non-null   object
 19  GO_terms                            3868 non-null   object
 20  GO_terms_human_readable             3868 non-null   object
 21  localization_keywords               3400 non-null   object
 22  parsed_functions                    3504 non-null   object
 23  parsed_PTMs                         2132 non-null   object
 24  ptm_bronze                          3083 non-null   object
 25  ptm_gold                            2720 non-null   object
 26  ptm_silver                          2396 non-null   object
 27  IDR_count                           3927 non-null   int64
 28  IDR_sequences                       3927 non-null   object
 29  IDR_ranges                          3927 non-null   object
 30  N_aa_disordered                     3927 non-null   int64
 31  disorder_fraction                   3876 non-null   float64
 32  is_disordered_0.05                  3927 non-null   int64
 33  is_disordered_0.10                  3927 non-null   int64
 34  is_disordered_0.15                  3927 non-null   int64
 35  is_disordered_0.20                  3927 non-null   int64
 36  is_disordered_0.25                  3927 non-null   int64
 37  is_disordered_0.30                  3927 non-null   int64
 38  is_disordered_0.35                  3927 non-null   int64
 39  is_disordered_0.40                  3927 non-null   int64
 40  is_disordered_0.45                  3927 non-null   int64
 41  is_disordered_0.50                  3927 non-null   int64
 42  is_disordered_0.55                  3927 non-null   int64
 43  is_disordered_0.60                  3927 non-null   int64
 44  is_disordered_0.65                  3927 non-null   int64
 45  is_disordered_0.70                  3927 non-null   int64
 46  is_disordered_0.75                  3927 non-null   int64
 47  is_disordered_0.80                  3927 non-null   int64
 48  is_disordered_0.85                  3927 non-null   int64
 49  is_disordered_0.90                  3927 non-null   int64
 50  is_disordered_0.95                  3927 non-null   int64
 51  is_disordered_1.00                  3927 non-null   int64
 52  albatross                           3075 non-null   object
 53  cider                               3075 non-null   object
dtypes: bool(1), float64(11), int64(23), object(19)
memory usage: 1.6+ MB

In [27]:
df.head(10)

,node,_wkshell,degree_centrality,betweenness_centrality,eigenvector_centrality,closeness_centrality,load_centrality,pagerank,information_centrality,CentralityCosDist_rank,...,is_disordered_0.65,is_disordered_0.70,is_disordered_0.75,is_disordered_0.80,is_disordered_0.85,is_disordered_0.90,is_disordered_0.95,is_disordered_1.00,albatross,cider
0,YKL063C,318,0.005094,0.002602,0.000072,0.259652,0.002563,0.000356,0.000570,2333.0,...,1,1,1,1,1,1,1,1,"{'1': {'idr_end_to_end': 93.099, 'idr_end_to_e...","{'1': {'Kappa': 0.12610556557774544, 'Length':..."
1,YDL223C,547,0.014519,0.014035,0.000536,0.302872,0.014291,0.001469,0.000619,2706.0,...,1,1,1,1,1,1,1,1,"{'1': {'idr_end_to_end': 245.184, 'idr_end_to_...","{'1': {'Kappa': 0.19430412352085114, 'Length':..."
2,YPL036W,748,0.029801,0.059166,0.004472,0.326912,0.058826,0.003300,0.000635,2945.0,...,0,0,0,0,0,0,0,0,"{'1': {'idr_end_to_end': 82.299, 'idr_end_to_e...","{'1': {'Kappa': 0.2817406952381134, 'Length': ..."
3,YPL050C,348,0.007387,0.000732,0.000008,0.245821,0.000743,0.000471,0.000590,2466.0,...,0,0,0,0,0,0,0,0,"{'1': {'idr_end_to_end': 48.521, 'idr_end_to_e...","{'1': {'Kappa': 0.2570025324821472, 'Length': ..."
4,YJR148W,391,0.008151,0.002525,0.000093,0.277862,0.002642,0.000645,0.000600,2460.0,...,0,0,0,0,0,0,0,0,"{'1': {'idr_end_to_end': 35.03, 'idr_end_to_en...","{'1': {'Kappa': 0.41875818371772766, 'Length':..."
5,YHR208W,301,0.004075,0.000726,0.000244,0.265007,0.000716,0.000295,0.000558,2271.0,...,0,0,0,0,0,0,0,0,"{'1': {'idr_end_to_end': 48.907, 'idr_end_to_e...","{'1': {'Kappa': 0.2526458278298378, 'Length': ..."
6,YBR035C,472,0.011462,0.001871,0.000127,0.282188,0.001712,0.000879,0.000613,2642.0,...,0,0,0,0,0,0,0,0,NaN,NaN
7,YPR008W,391,0.007132,0.008777,0.003376,0.293329,0.009230,0.000624,0.000590,2407.0,...,1,1,1,1,1,1,0,0,"{'1': {'idr_end_to_end': 179.158, 'idr_end_to_...","{'1': {'Kappa': 0.17223802208900452, 'Length':..."
8,YKL024C,510,0.012990,0.003456,0.000161,0.281764,0.003323,0.001068,0.000615,2708.0,...,0,0,0,0,0,0,0,0,NaN,NaN
9,YBR286W,176,0.002292,0.000001,0.000023,0.244492,0.000002,0.000193,0.000503,1975.0,...,0,0,0,0,0,0,0,0,"{'1': {'idr_end_to_end': 21.408, 'idr_end_to_e...","{'1': {'Kappa': -1.0, 'Length': 14, 'FCR': 0.0..."

In [42]:
test = df[df["node"] == "YKL063C"]
print (test["sequence"])
print (test["cleavage_site_start"])
print (test["signalP_trimmed_sequence"])

0    MQGDIRRKKDLLPRYKTGSKYNSRRRGGYLTTPMKKIIVYIILLCG...
Name: sequence, dtype: object
0   NaN
Name: cleavage_site_start, dtype: float64
0    MQGDIRRKKDLLPRYKTGSKYNSRRRGGYLTTPMKKIIVYIILLCG...
Name: signalP_trimmed_sequence, dtype: object

In [41]:
x = list(test["disorder_fraction"])
print (type(x[0]))
print (x[0])

<class 'float'>
1.0

In [ ]:
for i in range (0, len(x[0])):
    if x[0][i] > 0.5:
        print (i + 1, x[0][i], "Disordered")
    else:
        print (i + 1, x[0][i], "")

In [ ]:
df = pd.read_pickle("../4-idr-properties/processed-data/0-s288c-step4.pkl")

In [ ]:
temp = df[df["node"] == "YKL063C"]

In [ ]:
temp["IDR_count"][0]

In [30]:
temp["IDR_sequences"]

2    {'1': 'MSSTEAKQYKEKPSKEYLHASDGDDPANNSAASSSSSSS...
Name: IDR_sequences, dtype: object

In [31]:
temp["disorder_fraction"]

2    0.13622
Name: disorder_fraction, dtype: float64

In [32]:
temp = df[df["node"] == "YPL036W"]

In [33]:
temp["IDR_count"].iloc[0]

np.int64(1)

In [34]:
x = temp["IDR_sequences"].iloc[0]

In [35]:
x

{'1': 'MSSTEAKQYKEKPSKEYLHASDGDDPANNSAASSSSSSSTSTSASSSAAAVPRKAAAASAADDSDSDEDIDQLIDELQSNYGEGDESGEEEVRTDGVHAGQRVVPEKDLSTDPAY',
 '2': 'AAMQRVSTQHEKSS'}

In [36]:
len(x['1'])

115

In [12]:
temp.columns

Index(['node', '_wkshell', 'degree_centrality', 'betweenness_centrality',
       'eigenvector_centrality', 'closeness_centrality', 'load_centrality',
       'pagerank', 'information_centrality', 'CentralityCosDist_rank',
       'CentralityCosDist_similarity_score', 'has_verified_sequence',
       'sequence', 'UniProtKB-AC', 'DeepTMHMM_trimmed_sequence',
       'DeepTMHMM_class', 'cleavage_site_start', 'signalP_trimmed_sequence',
       'ProteinName', 'GO_terms', 'GO_terms_human_readable',
       'localization_keywords', 'parsed_functions', 'parsed_PTMs',
       'ptm_bronze', 'ptm_gold', 'ptm_silver', 'IDR_count', 'IDR_sequences',
       'IDR_ranges', 'N_aa_disordered', 'disorder_fraction',
       'is_disordered_0.05', 'is_disordered_0.10', 'is_disordered_0.15',
       'is_disordered_0.20', 'is_disordered_0.25', 'is_disordered_0.30',
       'is_disordered_0.35', 'is_disordered_0.40', 'is_disordered_0.45',
       'is_disordered_0.50', 'is_disordered_0.55', 'is_disordered_0.60',
       'is_disordered_0.65', 'is_disordered_0.70', 'is_disordered_0.75',
       'is_disordered_0.80', 'is_disordered_0.85', 'is_disordered_0.90',
       'is_disordered_0.95', 'is_disordered_1.00', 'albatross', 'cider'],
      dtype='object')

In [37]:
temp["IDR_ranges"].iloc[0]

{'1': '1-115', '2': '934-947'}

In [38]:
temp["albatross"].iloc[0]

{'1': {'idr_end_to_end': np.float32(82.299),
  'idr_end_to_end_scaled': np.float64(81.051),
  'idr_rg': np.float32(33.141),
  'idr_rg_scaled': np.float64(33.473),
  'idr_asphericity': np.float32(0.437),
  'idr_scaling_exponent': np.float32(0.567),
  'idr_prefactor': np.float32(5.914)},
 '2': {'idr_end_to_end': np.float64(23.442),
  'idr_end_to_end_scaled': np.float64(23.442),
  'idr_rg': np.float64(9.116),
  'idr_rg_scaled': np.float64(9.116),
  'idr_asphericity': np.float32(0.496),
  'idr_scaling_exponent': np.float32(0.504),
  'idr_prefactor': np.float32(5.968)}}

In [39]:
temp["cider"].iloc[0]

{'1': {'Kappa': 0.2817406952381134,
  'Length': 115,
  'FCR': 0.2956521739130435,
  'NCPR': -0.13913043478260873,
  'SHD': 5.302518933966918,
  'SCD': 4.120943816463007,
  'Molecular_weight': 11917.100000000031,
  'F_Neg': 0.2173913043478261,
  'F_Pos': 0.07826086956521738,
  'Hydrophobicity': np.float64(3.4991304347826087),
  'Fraction_aromatic': 0.034782608695652174,
  'Fraction_aliphatic': 0.25217391304347825,
  'Fraction_polar': 0.3739130434782609,
  'Complexity': 0.8429965399079754,
  'Amino_Acid_Fraction_A': 0.1478,
  'Amino_Acid_Fraction_C': 0.0,
  'Amino_Acid_Fraction_D': 0.1217,
  'Amino_Acid_Fraction_E': 0.0957,
  'Amino_Acid_Fraction_F': 0.0,
  'Amino_Acid_Fraction_G': 0.0522,
  'Amino_Acid_Fraction_H': 0.0174,
  'Amino_Acid_Fraction_I': 0.0174,
  'Amino_Acid_Fraction_K': 0.0522,
  'Amino_Acid_Fraction_L': 0.0348,
  'Amino_Acid_Fraction_M': 0.0087,
  'Amino_Acid_Fraction_N': 0.0261,
  'Amino_Acid_Fraction_P': 0.0435,
  'Amino_Acid_Fraction_Q': 0.0348,
  'Amino_Acid_Fraction_R': 0.0261,
  'Amino_Acid_Fraction_S': 0.2,
  'Amino_Acid_Fraction_T': 0.0435,
  'Amino_Acid_Fraction_V': 0.0435,
  'Amino_Acid_Fraction_W': 0.0,
  'Amino_Acid_Fraction_Y': 0.0348},
 '2': {'Kappa': 0.2816631942987442,
  'Length': 14,
  'FCR': 0.21428571428571427,
  'NCPR': 0.07142857142857142,
  'SHD': 2.5972209459191595,
  'SCD': 0.014018683448672345,
  'Molecular_weight': 1559.9999999999998,
  'F_Neg': 0.07142857142857142,
  'F_Pos': 0.14285714285714285,
  'Hydrophobicity': np.float64(3.3928571428571432),
  'Fraction_aromatic': 0.0,
  'Fraction_aliphatic': 0.2857142857142857,
  'Fraction_polar': 0.4999999999999999,
  'Complexity': 0.736246819683182,
  'Amino_Acid_Fraction_A': 0.1429,
  'Amino_Acid_Fraction_C': 0.0,
  'Amino_Acid_Fraction_D': 0.0,
  'Amino_Acid_Fraction_E': 0.0714,
  'Amino_Acid_Fraction_F': 0.0,
  'Amino_Acid_Fraction_G': 0.0,
  'Amino_Acid_Fraction_H': 0.0714,
  'Amino_Acid_Fraction_I': 0.0,
  'Amino_Acid_Fraction_K': 0.0714,
  'Amino_Acid_Fraction_L': 0.0,
  'Amino_Acid_Fraction_M': 0.0714,
  'Amino_Acid_Fraction_N': 0.0,
  'Amino_Acid_Fraction_P': 0.0,
  'Amino_Acid_Fraction_Q': 0.1429,
  'Amino_Acid_Fraction_R': 0.0714,
  'Amino_Acid_Fraction_S': 0.2143,
  'Amino_Acid_Fraction_T': 0.0714,
  'Amino_Acid_Fraction_V': 0.0714,
  'Amino_Acid_Fraction_W': 0.0,
  'Amino_Acid_Fraction_Y': 0.0}}

In [40]:
df.tail()["albatross"]

3922    {'1': {'idr_end_to_end': 26.889, 'idr_end_to_e...
3923    {'1': {'idr_end_to_end': 34.249, 'idr_end_to_e...
3924                                                  NaN
3925    {'1': {'idr_end_to_end': 43.824, 'idr_end_to_e...
3926                                                  NaN
Name: albatross, dtype: object

In [43]:
df = pd.read_pickle("../5-dG-calculations/processed-data/0-s288c-temp.pkl")

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3927 entries, 0 to 3926
Data columns (total 65 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   node                                3927 non-null   object
 1   _wkshell                            3927 non-null   int64
 2   degree_centrality                   3927 non-null   float64
 3   betweenness_centrality              3927 non-null   float64
 4   eigenvector_centrality              3927 non-null   float64
 5   closeness_centrality                3927 non-null   float64
 6   load_centrality                     3927 non-null   float64
 7   pagerank                            3927 non-null   float64
 8   information_centrality              3927 non-null   float64
 9   CentralityCosDist_rank              3927 non-null   float64
 10  CentralityCosDist_similarity_score  3927 non-null   float64
 11  has_verified_sequence               3927 non-null   bool
 12  sequence                            3876 non-null   object
 13  UniProtKB-AC                        3885 non-null   object
 14  DeepTMHMM_trimmed_sequence          3875 non-null   object
 15  DeepTMHMM_class                     3876 non-null   object
 16  cleavage_site_start                 129 non-null    float64
 17  signalP_trimmed_sequence            3876 non-null   object
 18  ProteinName                         3885 non-null   object
 19  GO_terms                            3868 non-null   object
 20  GO_terms_human_readable             3868 non-null   object
 21  localization_keywords               3400 non-null   object
 22  parsed_functions                    3504 non-null   object
 23  parsed_PTMs                         2132 non-null   object
 24  ptm_bronze                          3083 non-null   object
 25  ptm_gold                            2720 non-null   object
 26  ptm_silver                          2396 non-null   object
 27  IDR_count                           3927 non-null   int64
 28  IDR_sequences                       3927 non-null   object
 29  IDR_ranges                          3927 non-null   object
 30  N_aa_disordered                     3927 non-null   int64
 31  disorder_fraction                   3876 non-null   float64
 32  is_disordered_0.05                  3927 non-null   int64
 33  is_disordered_0.10                  3927 non-null   int64
 34  is_disordered_0.15                  3927 non-null   int64
 35  is_disordered_0.20                  3927 non-null   int64
 36  is_disordered_0.25                  3927 non-null   int64
 37  is_disordered_0.30                  3927 non-null   int64
 38  is_disordered_0.35                  3927 non-null   int64
 39  is_disordered_0.40                  3927 non-null   int64
 40  is_disordered_0.45                  3927 non-null   int64
 41  is_disordered_0.50                  3927 non-null   int64
 42  is_disordered_0.55                  3927 non-null   int64
 43  is_disordered_0.60                  3927 non-null   int64
 44  is_disordered_0.65                  3927 non-null   int64
 45  is_disordered_0.70                  3927 non-null   int64
 46  is_disordered_0.75                  3927 non-null   int64
 47  is_disordered_0.80                  3927 non-null   int64
 48  is_disordered_0.85                  3927 non-null   int64
 49  is_disordered_0.90                  3927 non-null   int64
 50  is_disordered_0.95                  3927 non-null   int64
 51  is_disordered_1.00                  3927 non-null   int64
 52  albatross                           3075 non-null   object
 53  cider                               3075 non-null   object
 54  structure_path                      3885 non-null   object
 55  structure_exists                    3927 non-null   int64
 56  structure_fasta_path                3885 non-null   object
 57  structure_sequence                  3873 non-null   object
 58  cleaved_structure_path              129 non-null    object
 59  cleaved_structure_sequence          3873 non-null   object
 60  sequence_matches_structure          3927 non-null   bool
 61  final_structure_path                3873 non-null   object
 62  final_sequence                      3873 non-null   object
 63  final_structure_source              3927 non-null   object
 64  mean_plddt                          3873 non-null   float64
dtypes: bool(2), float64(12), int64(24), object(27)
memory usage: 1.9+ MB

In [45]:
df["final_structure_source"].value_counts()

final_structure_source
EBI            3730
AF2-cleaved     129
None             54
AF2              14
Name: count, dtype: int64

In [57]:
df = pd.read_pickle("../5-dG-calculations/processed-data/0-s288c-step5.pkl")

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3927 entries, 0 to 3926
Data columns (total 71 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   node                                3927 non-null   object
 1   _wkshell                            3927 non-null   int64
 2   degree_centrality                   3927 non-null   float64
 3   betweenness_centrality              3927 non-null   float64
 4   eigenvector_centrality              3927 non-null   float64
 5   closeness_centrality                3927 non-null   float64
 6   load_centrality                     3927 non-null   float64
 7   pagerank                            3927 non-null   float64
 8   information_centrality              3927 non-null   float64
 9   CentralityCosDist_rank              3927 non-null   float64
 10  CentralityCosDist_similarity_score  3927 non-null   float64
 11  has_verified_sequence               3927 non-null   bool
 12  sequence                            3876 non-null   object
 13  UniProtKB-AC                        3885 non-null   object
 14  DeepTMHMM_trimmed_sequence          3875 non-null   object
 15  DeepTMHMM_class                     3876 non-null   object
 16  cleavage_site_start                 129 non-null    float64
 17  signalP_trimmed_sequence            3876 non-null   object
 18  ProteinName                         3885 non-null   object
 19  GO_terms                            3868 non-null   object
 20  GO_terms_human_readable             3868 non-null   object
 21  localization_keywords               3400 non-null   object
 22  parsed_functions                    3504 non-null   object
 23  parsed_PTMs                         2132 non-null   object
 24  ptm_bronze                          3083 non-null   object
 25  ptm_gold                            2720 non-null   object
 26  ptm_silver                          2396 non-null   object
 27  IDR_count                           3927 non-null   int64
 28  IDR_sequences                       3927 non-null   object
 29  IDR_ranges                          3927 non-null   object
 30  N_aa_disordered                     3927 non-null   int64
 31  disorder_fraction                   3876 non-null   float64
 32  is_disordered_0.05                  3927 non-null   int64
 33  is_disordered_0.10                  3927 non-null   int64
 34  is_disordered_0.15                  3927 non-null   int64
 35  is_disordered_0.20                  3927 non-null   int64
 36  is_disordered_0.25                  3927 non-null   int64
 37  is_disordered_0.30                  3927 non-null   int64
 38  is_disordered_0.35                  3927 non-null   int64
 39  is_disordered_0.40                  3927 non-null   int64
 40  is_disordered_0.45                  3927 non-null   int64
 41  is_disordered_0.50                  3927 non-null   int64
 42  is_disordered_0.55                  3927 non-null   int64
 43  is_disordered_0.60                  3927 non-null   int64
 44  is_disordered_0.65                  3927 non-null   int64
 45  is_disordered_0.70                  3927 non-null   int64
 46  is_disordered_0.75                  3927 non-null   int64
 47  is_disordered_0.80                  3927 non-null   int64
 48  is_disordered_0.85                  3927 non-null   int64
 49  is_disordered_0.90                  3927 non-null   int64
 50  is_disordered_0.95                  3927 non-null   int64
 51  is_disordered_1.00                  3927 non-null   int64
 52  albatross                           3075 non-null   object
 53  cider                               3075 non-null   object
 54  structure_path                      3885 non-null   object
 55  structure_exists                    3927 non-null   int64
 56  structure_fasta_path                3885 non-null   object
 57  structure_sequence                  3873 non-null   object
 58  cleaved_structure_path              129 non-null    object
 59  cleaved_structure_sequence          3873 non-null   object
 60  sequence_matches_structure          3927 non-null   bool
 61  final_structure_path                3873 non-null   object
 62  final_sequence                      3873 non-null   object
 63  final_structure_source              3927 non-null   object
 64  mean_plddt                          3873 non-null   float64
 65  L                                   3354 non-null   float64
 66  dH                                  3354 non-null   object
 67  dCp                                 3354 non-null   object
 68  dS                                  3354 non-null   object
 69  Ghosh-Dill-dG                       3354 non-null   float64
 70  cagiada-dG                          3354 non-null   float64
dtypes: bool(2), float64(15), int64(24), object(30)
memory usage: 2.1+ MB

In [59]:
df.head()

,node,_wkshell,degree_centrality,betweenness_centrality,eigenvector_centrality,closeness_centrality,load_centrality,pagerank,information_centrality,CentralityCosDist_rank,...,final_structure_path,final_sequence,final_structure_source,mean_plddt,L,dH,dCp,dS,Ghosh-Dill-dG,cagiada-dG
0,YKL063C,318,0.005094,0.002602,0.000072,0.259652,0.002563,0.000356,0.000570,2333.0,...,0-download-inputs/data-files/AF-P35725-F1-mode...,MQGDIRRKKDLLPRYKTGSKYNSRRRGGYLTTPMKKIIVYIILLCG...,EBI,63.869820,NaN,NaN,NaN,NaN,NaN,NaN
1,YDL223C,547,0.014519,0.014035,0.000536,0.302872,0.014291,0.001469,0.000619,2706.0,...,0-download-inputs/data-files/AF-Q07653-F1-mode...,MNMNESISKDGQGEEEQNNFSFGGKPGSYDSNSDSAQRKKSFSTTK...,EBI,34.082141,1046.0,-5302.9800000000005 kilojoule / mole,-64.322 kilojoule / kelvin / mole,-17.657799999999998 kilojoule / kelvin / mole,-21.921468,10.666313
2,YPL036W,748,0.029801,0.059166,0.004472,0.326912,0.058826,0.003300,0.000635,2945.0,...,0-download-inputs/data-files/AF-P19657-F1-mode...,MSSTEAKQYKEKPSKEYLHASDGDDPANNSAASSSSSSSTSTSASS...,EBI,76.446990,NaN,NaN,NaN,NaN,NaN,NaN
3,YPL050C,348,0.007387,0.000732,0.000008,0.245821,0.000743,0.000471,0.000590,2466.0,...,0-download-inputs/data-files/AF-P39107-F1-mode...,MSLSLVSYRLRKNPWVNIFLPVLAIFLIYIIFFQRDQSLLGLNGQS...,EBI,83.304886,395.0,-2028.45 kilojoule / mole,-23.959999999999997 kilojoule / kelvin / mole,-6.721 kilojoule / kelvin / mole,-10.567557,17.733361
4,YJR148W,391,0.008151,0.002525,0.000093,0.277862,0.002642,0.000645,0.000600,2460.0,...,0-download-inputs/data-files/AF-P47176-F1-mode...,MTLAPLDASKVKITTTQHASKPKPNSELVFGKSFTDHMLTAEWTAE...,EBI,96.190612,376.0,-1932.88 kilojoule / mole,-22.782 kilojoule / kelvin / mole,-6.401800000000001 kilojoule / kelvin / mole,-10.236183,26.490762

In [52]:
df["final_structure_source"].value_counts()

final_structure_source
EBI            3730
AF2-cleaved     129
None             54
AF2              14
Name: count, dtype: int64

In [53]:
df["DeepTMHMM_class"].value_counts()

DeepTMHMM_class
GLOB     3273
TM        457
SP         84
SP+TM      61
BETA        1
Name: count, dtype: int64

In [61]:
df[df["node"] == "YKL063C"]["DeepTMHMM_class"]

0    TM
Name: DeepTMHMM_class, dtype: object

In [69]:
df = pd.read_pickle("../7-FoldX-scoring/processed-data/0-s288c-step7.pkl")

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3927 entries, 0 to 3926
Data columns (total 99 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   node                                3927 non-null   object
 1   _wkshell                            3927 non-null   int64
 2   degree_centrality                   3927 non-null   float64
 3   betweenness_centrality              3927 non-null   float64
 4   eigenvector_centrality              3927 non-null   float64
 5   closeness_centrality                3927 non-null   float64
 6   load_centrality                     3927 non-null   float64
 7   pagerank                            3927 non-null   float64
 8   information_centrality              3927 non-null   float64
 9   CentralityCosDist_rank              3927 non-null   float64
 10  CentralityCosDist_similarity_score  3927 non-null   float64
 11  has_verified_sequence               3927 non-null   bool
 12  sequence                            3876 non-null   object
 13  UniProtKB-AC                        3885 non-null   object
 14  DeepTMHMM_trimmed_sequence          3875 non-null   object
 15  DeepTMHMM_class                     3876 non-null   object
 16  cleavage_site_start                 129 non-null    float64
 17  signalP_trimmed_sequence            3876 non-null   object
 18  ProteinName                         3885 non-null   object
 19  GO_terms                            3868 non-null   object
 20  GO_terms_human_readable             3868 non-null   object
 21  localization_keywords               3400 non-null   object
 22  parsed_functions                    3504 non-null   object
 23  parsed_PTMs                         2132 non-null   object
 24  ptm_bronze                          3083 non-null   object
 25  ptm_gold                            2720 non-null   object
 26  ptm_silver                          2396 non-null   object
 27  IDR_count                           3927 non-null   int64
 28  IDR_sequences                       3927 non-null   object
 29  IDR_ranges                          3927 non-null   object
 30  N_aa_disordered                     3927 non-null   int64
 31  disorder_fraction                   3876 non-null   float64
 32  is_disordered_0.05                  3927 non-null   int64
 33  is_disordered_0.10                  3927 non-null   int64
 34  is_disordered_0.15                  3927 non-null   int64
 35  is_disordered_0.20                  3927 non-null   int64
 36  is_disordered_0.25                  3927 non-null   int64
 37  is_disordered_0.30                  3927 non-null   int64
 38  is_disordered_0.35                  3927 non-null   int64
 39  is_disordered_0.40                  3927 non-null   int64
 40  is_disordered_0.45                  3927 non-null   int64
 41  is_disordered_0.50                  3927 non-null   int64
 42  is_disordered_0.55                  3927 non-null   int64
 43  is_disordered_0.60                  3927 non-null   int64
 44  is_disordered_0.65                  3927 non-null   int64
 45  is_disordered_0.70                  3927 non-null   int64
 46  is_disordered_0.75                  3927 non-null   int64
 47  is_disordered_0.80                  3927 non-null   int64
 48  is_disordered_0.85                  3927 non-null   int64
 49  is_disordered_0.90                  3927 non-null   int64
 50  is_disordered_0.95                  3927 non-null   int64
 51  is_disordered_1.00                  3927 non-null   int64
 52  albatross                           3075 non-null   object
 53  cider                               3075 non-null   object
 54  structure_path                      3885 non-null   object
 55  structure_exists                    3927 non-null   int64
 56  structure_fasta_path                3885 non-null   object
 57  structure_sequence                  3873 non-null   object
 58  cleaved_structure_path              129 non-null    object
 59  cleaved_structure_sequence          3873 non-null   object
 60  sequence_matches_structure          3927 non-null   bool
 61  final_structure_path                3873 non-null   object
 62  final_sequence                      3873 non-null   object
 63  final_structure_source              3927 non-null   object
 64  mean_plddt                          3873 non-null   float64
 65  L                                   3354 non-null   float64
 66  dH                                  3354 non-null   object
 67  dCp                                 3354 non-null   object
 68  dS                                  3354 non-null   object
 69  Ghosh-Dill-dG                       3354 non-null   float64
 70  cagiada-dG                          3354 non-null   float64
 71  Rosetta_total_score_0001            3354 non-null   float64
 72  Rosetta_total_score_0002            3354 non-null   float64
 73  Rosetta_total_score_0003            3354 non-null   float64
 74  Rosetta_total_score_0004            3354 non-null   float64
 75  Rosetta_total_score_0005            3354 non-null   float64
 76  Rosetta_total_score_0006            3354 non-null   float64
 77  Rosetta_total_score_0007            3354 non-null   float64
 78  Rosetta_total_score_0008            3354 non-null   float64
 79  Rosetta_total_score_0009            3354 non-null   float64
 80  Rosetta_total_score_0010            3354 non-null   float64
 81  Rosetta_best_total_score            3354 non-null   float64
 82  Rosetta_best_pose_index             3354 non-null   float64
 83  Rosetta_best_score_file             3354 non-null   object
 84  Rosetta_n_found                     3927 non-null   float64
 85  FoldX_total_energy_0001             3354 non-null   float64
 86  FoldX_total_energy_0002             3354 non-null   float64
 87  FoldX_total_energy_0003             3354 non-null   float64
 88  FoldX_total_energy_0004             3354 non-null   float64
 89  FoldX_total_energy_0005             3354 non-null   float64
 90  FoldX_total_energy_0006             3354 non-null   float64
 91  FoldX_total_energy_0007             3354 non-null   float64
 92  FoldX_total_energy_0008             3354 non-null   float64
 93  FoldX_total_energy_0009             3354 non-null   float64
 94  FoldX_total_energy_0010             3354 non-null   float64
 95  FoldX_best_total_energy             3354 non-null   float64
 96  FoldX_best_pose_index               3354 non-null   float64
 97  FoldX_best_file                     3354 non-null   object
 98  FoldX_n_found                       3927 non-null   float64
dtypes: bool(2), float64(41), int64(24), object(32)
memory usage: 2.9+ MB

In [64]:
temp = df.iloc[1200]

In [73]:
for index, row in df.iterrows():
    print(index, row["DeepTMHMM_class"], row["node"], row["FoldX_total_energy_0001"], row["FoldX_total_energy_0002"],row["FoldX_total_energy_0003"],row["FoldX_total_energy_0004"],row["FoldX_total_energy_0005"],row["FoldX_total_energy_0006"],row["FoldX_total_energy_0007"],row["FoldX_total_energy_0008"],row["FoldX_total_energy_0009"],row["FoldX_total_energy_0010"],row["FoldX_best_total_energy"])

0 TM YKL063C nan nan nan nan nan nan nan nan nan nan nan
1 GLOB YDL223C 1803.02 1943.21 1927.03 1923.43 1933.66 1597.66 1722.09 1936.0 1932.87 1587.75 1587.75
2 TM YPL036W nan nan nan nan nan nan nan nan nan nan nan
3 GLOB YPL050C 143.055 135.291 132.913 133.564 126.624 132.642 127.647 139.41 142.554 139.748 126.624
4 GLOB YJR148W 29.9363 27.0219 33.103 26.2652 36.1022 29.5296 36.4064 34.0612 38.9228 34.3358 26.2652
5 GLOB YHR208W 47.456 43.2527 41.5459 50.9152 43.762 46.6277 44.0843 57.6915 43.4075 45.719 41.5459
6 GLOB YBR035C 79.8046 76.9389 78.9593 78.7204 93.7624 89.5745 80.8155 77.9679 85.5811 87.3582 76.9389
7 GLOB YPR008W 1327.5 1428.4 1047.9 1132.24 1163.69 1079.38 1659.65 1579.13 1559.52 1126.95 1047.9
8 GLOB YKL024C 28.6481 27.5201 30.5501 22.608 27.9764 26.3006 24.5855 28.5775 28.2657 22.9222 22.608
9 SP YBR286W 221.065 225.403 210.608 207.112 223.095 216.615 207.219 224.174 250.514 221.582 207.112
10 GLOB YLR420W 75.7043 80.2875 77.1114 69.4777 77.2303 82.2002 81.9413 79.8667 80.693 79.6779 69.4777
11 GLOB YKR066C 89.022 97.4785 110.993 104.72 105.804 98.7059 103.478 95.286 95.1777 96.656 89.022
12 GLOB YNL117W 43.3184 36.1835 33.0029 38.7178 46.9461 35.5339 41.1704 34.2305 28.5828 34.2216 28.5828
13 GLOB YNL015W 18.462 15.7354 17.5795 17.7143 17.3222 17.9213 16.6804 16.8994 16.5628 18.8977 15.7354
14 GLOB YOR285W 21.9678 27.8061 29.1025 24.2277 28.8056 28.9712 25.5931 32.0731 22.6984 30.1221 21.9678
15 GLOB YOR239W 928.767 756.656 756.653 822.355 1037.97 998.586 641.075 869.04 1158.08 906.586 641.075
16 GLOB YJL055W 89.7079 82.9264 87.3255 81.6478 81.4932 87.261 90.5523 87.3834 83.7041 89.5944 81.4932
17 GLOB YJL066C 101.206 104.577 90.9768 95.4486 100.809 95.7496 98.3793 98.4992 103.692 100.211 90.9768
18 nan YGR027W-A;YGR038C-A;YJR026W;YLR227W-A;YML040W nan nan nan nan nan nan nan nan nan nan nan
19 GLOB YGL087C 18.8784 14.1795 16.0425 22.4285 20.5368 19.6387 17.5325 22.7317 21.0834 15.7163 14.1795
20 GLOB YNL134C 23.7034 26.3219 30.893 27.0213 25.1142 28.1499 29.1575 32.4028 31.0545 35.0067 23.7034
21 GLOB YNR034W-A 29.7622 32.1538 30.3101 32.1879 30.7583 30.6046 33.1028 32.0839 32.4862 29.1929 29.1929
22 GLOB YPL111W 65.6119 71.0079 67.1269 68.2554 73.5309 84.1652 80.6644 71.8494 68.045 68.044 65.6119
23 GLOB YIR037W 6.72324 10.8723 4.79454 6.55602 5.68688 8.21371 7.67908 7.80486 5.41849 7.20389 4.79454
24 GLOB YML022W -3.81791 -1.18777 -6.61068 -3.43219 3.98771 0.135513 -1.21971 -0.676146 -2.99503 0.803208 -6.61068
25 GLOB YNL104C 132.584 137.379 140.88 125.04 124.859 134.489 125.49 133.004 138.531 136.001 124.859
26 SP YEL060C 686.186 556.453 488.668 577.383 495.476 658.404 612.706 681.547 693.024 553.419 488.668
27 GLOB YOR168W 181.989 135.807 133.869 136.673 127.616 129.023 140.394 121.707 136.753 135.626 121.707
28 GLOB YER175C 64.7497 46.8315 47.9726 45.1717 48.033 50.6005 53.1097 50.2482 49.7352 50.0166 45.1717
29 GLOB YEL071W 124.42 124.85 122.723 112.33 128.969 132.383 123.071 121.705 123.593 116.579 112.33
30 GLOB YBR222C 93.1187 96.9401 89.3846 81.407 100.102 90.3409 95.7889 84.7069 84.4617 105.082 81.407
31 GLOB YOR323C 74.1694 77.1514 84.7857 75.639 78.5953 73.7829 77.8527 80.1232 81.773 80.243 73.7829
32 GLOB YBL037W 133.497 154.538 128.456 134.994 130.304 140.145 131.674 129.948 138.022 118.395 118.395
33 GLOB YOL062C 142.048 149.225 146.383 158.334 155.741 145.159 145.994 140.547 152.809 147.989 140.547
34 GLOB YJR005W 106.638 104.614 115.018 98.3121 107.484 121.636 109.92 109.713 110.22 106.599 98.3121
35 GLOB YLR352W 335.477 325.094 356.041 350.963 331.652 334.842 322.109 336.079 337.733 329.719 322.109
36 GLOB YNL059C 162.643 171.605 173.138 165.098 163.132 167.437 175.626 164.026 162.584 180.205 162.584
37 GLOB YBL024W 160.473 165.831 170.728 150.902 159.286 162.605 173.056 174.876 151.362 158.178 150.902
38 GLOB YDR356W 511.444 1090.71 696.6 1116.24 949.301 1048.18 805.695 546.505 736.996 623.156 511.444
39 GLOB YBR149W 45.5258 36.8024 34.7339 39.8361 42.9055 31.7987 41.5371 39.3111 38.3911 33.5249 31.7987
40 GLOB YDR037W 133.763 144.982 142.331 141.182 147.013 138.233 139.928 136.141 148.824 155.352 133.763
41 GLOB YLR421C 67.6579 74.6777 70.2113 73.9988 70.4662 69.6289 71.0181 71.6742 63.5993 70.5726 63.5993
42 SP+TM YFL048C nan nan nan nan nan nan nan nan nan nan nan
43 TM YDR270W nan nan nan nan nan nan nan nan nan nan nan
44 GLOB YKL042W 472.235 326.74 347.209 412.148 437.993 444.852 349.686 312.069 374.569 365.282 312.069
45 GLOB YHR019C 99.4308 88.1807 87.4678 84.6773 97.9763 103.175 96.0048 90.9293 93.6814 87.5888 84.6773
46 GLOB YLL018C 146.759 156.12 149.549 149.96 150.475 156.353 151.108 151.541 152.019 156.53 146.759
47 GLOB YKL103C 139.656 128.394 128.456 128.421 122.808 122.663 128.519 127.972 127.919 125.121 122.663
48 SP+TM YLR080W nan nan nan nan nan nan nan nan nan nan nan
49 TM YLR072W nan nan nan nan nan nan nan nan nan nan nan
50 GLOB YNL225C 286.128 288.24 283.893 556.887 360.368 291.542 292.024 291.664 292.919 283.472 283.472
51 SP YLR250W 104.524 106.333 105.84 103.715 108.275 98.6014 105.782 107.079 104.486 100.783 98.6014
52 TM YOL158C nan nan nan nan nan nan nan nan nan nan nan
53 GLOB YNL231C 72.1775 85.115 70.2712 78.5179 75.1527 74.9489 70.8111 77.5634 71.5462 76.8464 70.2712
54 GLOB YOR373W 1245.79 1091.76 897.542 736.376 751.598 946.332 1030.53 789.929 1030.29 1062.42 736.376
55 GLOB YPL124W 218.834 216.156 331.736 254.649 250.983 304.48 215.732 328.546 217.695 225.853 215.732
56 GLOB YDL201W 65.7524 66.8006 58.304 68.3254 72.6346 68.9736 56.7874 55.3038 64.0284 69.9163 55.3038
57 GLOB YDL195W 1442.33 1443.94 1415.81 1260.24 1454.87 1432.89 1720.11 1353.52 1449.54 1437.25 1260.24
58 GLOB YDR091C 81.6431 74.4444 71.4219 76.3872 79.9922 85.0404 72.3026 62.7776 76.5551 83.9788 62.7776
59 GLOB YEL034W 40.8631 39.7013 51.2194 40.7556 41.5528 42.3905 40.2582 35.4044 39.8894 37.629 35.4044
60 GLOB YDR388W 196.474 411.596 460.597 408.862 204.96 334.949 219.386 225.728 773.522 434.69 196.474
61 GLOB YER007C-A 23.7293 28.7385 28.4398 24.0289 28.8767 21.0609 23.313 29.1424 26.3237 27.6439 21.0609
62 TM YEL065W nan nan nan nan nan nan nan nan nan nan nan
63 GLOB YER178W 144.958 145.179 148.384 138.263 141.904 133.214 154.87 145.979 143.547 142.28 133.214
64 GLOB YER048C 74.0834 77.8775 74.473 80.5028 60.9954 79.9597 77.8444 75.9884 74.4065 84.2288 60.9954
65 GLOB YGL245W 120.628 116.32 118.241 107.442 111.925 106.86 110.057 113.243 99.5764 116.642 99.5764
66 GLOB YFR009W 206.941 201.974 202.802 194.696 196.096 199.023 192.563 202.452 187.081 188.681 187.081
67 GLOB YHR020W 147.635 154.803 145.752 140.016 152.963 149.31 148.474 148.417 161.94 146.724 140.016
68 GLOB YJR014W 61.9792 61.4517 67.3574 63.118 63.6618 64.9105 63.9374 57.7709 60.8657 59.5116 57.7709
69 GLOB YNL247W 190.877 164.245 169.558 169.708 162.238 155.934 170.943 169.243 163.049 169.195 155.934
70 GLOB YLR244C 151.962 150.657 150.423 149.578 157.305 156.472 156.545 153.749 155.044 149.364 149.364
71 GLOB YOL111C 105.975 103.777 98.065 109.472 100.185 100.528 100.79 101.545 97.9649 101.271 97.9649
72 GLOB YOR187W 102.24 110.915 103.419 106.583 107.377 96.0857 109.581 108.316 90.6185 100.129 90.6185
73 GLOB YPL048W 87.8139 91.0849 92.2742 100.494 89.0878 111.02 93.167 100.918 108.29 109.433 87.8139
74 GLOB YPR163C 484.577 444.803 429.203 524.683 594.325 415.57 781.746 401.498 494.148 900.433 401.498
75 TM YDR406W nan nan nan nan nan nan nan nan nan nan nan
76 SP+TM YMR058W nan nan nan nan nan nan nan nan nan nan nan
77 GLOB YPR154W 240.462 162.446 144.108 173.115 233.005 150.195 249.938 163.241 242.982 232.738 144.108
78 GLOB YGR185C 69.9038 66.3871 69.7267 56.2988 63.4153 72.3194 63.2296 70.6494 67.2152 76.2173 56.2988
79 GLOB YDL182W 102.936 99.557 96.5083 100.118 90.1325 90.09 92.3766 91.403 95.1577 92.2693 90.09
80 GLOB YGR054W 257.981 357.893 238.392 240.76 299.395 244.652 220.879 369.151 278.23 271.297 220.879
81 GLOB YGR285C 105.672 108.59 108.069 108.677 112.414 111.488 111.355 113.563 104.185 115.933 104.185
82 GLOB YHR064C 112.457 111.185 112.974 111.711 112.131 110.71 104.641 109.558 114.573 100.68 100.68
83 GLOB YJR047C 42.637 46.1328 41.9965 41.815 40.0671 40.1112 40.9929 39.4276 46.9955 38.8118 38.8118
84 GLOB YIL078W 138.491 128.84 136.929 139.045 120.7 122.523 133.256 115.216 130.487 136.305 115.216
85 GLOB YPL160W 133.102 110.956 150.021 129.469 126.226 128.145 125.576 134.906 108.928 111.442 108.928
86 GLOB YPR033C 159.112 155.203 169.982 156.129 170.181 165.254 154.558 158.922 167.476 175.355 154.558
87 TM YCL001W nan nan nan nan nan nan nan nan nan nan nan
88 TM YDL072C nan nan nan nan nan nan nan nan nan nan nan
89 TM YDL015C nan nan nan nan nan nan nan nan nan nan nan
90 SP YDR144C 277.404 326.878 348.094 284.844 273.34 281.667 279.556 340.443 269.393 272.081 269.393
91 GLOB YDR245W 147.07 130.899 134.306 137.517 133.695 144.83 133.547 132.707 146.778 145.547 130.899
92 TM YEL036C nan nan nan nan nan nan nan nan nan nan nan
93 GLOB YGL105W 118.903 133.168 125.033 125.662 129.319 129.659 130.3 126.456 131.953 287.003 118.903
94 GLOB YFR024C-A 434.409 302.226 429.105 476.885 400.547 290.166 444.548 298.085 333.074 416.935 290.166
95 SP YJL171C 122.119 117.104 119.729 121.871 118.377 119.696 120.649 118.121 118.079 109.034 109.034
96 SP+TM YGL200C nan nan nan nan nan nan nan nan nan nan nan
97 TM YKL065C nan nan nan nan nan nan nan nan nan nan nan
98 TM YKL165C nan nan nan nan nan nan nan nan nan nan nan
99 GLOB YLR386W 583.167 554.211 290.778 456.68 216.069 598.28 735.543 1243.3 531.338 474.003 216.069
100 GLOB YML115C 174.971 180.03 169.921 173.416 171.531 167.754 183.489 179.272 174.31 178.447 167.754
101 TM YML067C nan nan nan nan nan nan nan nan nan nan nan
102 GLOB YNL121C 89.6016 78.8433 87.286 80.4491 88.529 81.7377 96.4958 86.2725 96.1689 95.1491 78.8433
103 SP YMR008C 212.463 223.318 276.506 210.863 418.615 196.675 225.378 298.762 206.82 195.954 195.954
104 TM YOR153W nan nan nan nan nan nan nan nan nan nan nan
105 SP+TM YOR016C nan nan nan nan nan nan nan nan nan nan nan
106 GLOB YGR094W 175.902 175.945 196.267 179.743 259.179 215.427 216.748 169.818 164.81 600.721 164.81
107 GLOB YJL080C 397.799 838.974 449.884 391.041 580.405 676.262 481.331 385.797 406.461 772.253 385.797
108 GLOB YKL081W 52.646 51.6276 44.0212 50.2552 61.7401 59.9515 55.2244 49.2616 50.3274 54.2967 44.0212
109 GLOB YBR025C 46.3519 43.9081 47.2488 40.7953 43.9499 41.4694 39.7043 49.375 41.8211 41.5799 39.7043
110 GLOB YLR109W 25.3982 29.3687 28.3685 30.0632 29.32 28.3684 25.6392 27.3612 25.6148 28.8375 25.3982
111 GLOB YOL082W 661.567 372.141 1560.55 350.572 567.832 458.653 533.806 585.399 448.707 334.357 334.357
112 GLOB YGL156W 240.824 235.236 224.695 238.402 247.158 241.646 222.5 235.992 234.246 236.644 222.5
113 TM YAL042W nan nan nan nan nan nan nan nan nan nan nan
114 SP+TM YAL007C nan nan nan nan nan nan nan nan nan nan nan
115 SP+TM YBR187W nan nan nan nan nan nan nan nan nan nan nan
116 SP+TM YAR002C-A nan nan nan nan nan nan nan nan nan nan nan
117 TM YGL167C nan nan nan nan nan nan nan nan nan nan nan
118 TM YBR205W nan nan nan nan nan nan nan nan nan nan nan
119 GLOB YHR034C 233.965 407.309 375.555 352.978 238.654 186.984 254.176 271.071 424.631 210.851 186.984
120 GLOB YMR038C 77.1014 76.0603 83.8506 76.996 87.0982 85.1326 91.7306 86.5714 82.6131 84.9462 76.0603
121 GLOB YNL208W 501.508 406.798 461.892 349.3 360.986 406.843 473.855 269.424 472.216 294.659 269.424
122 TM YBR096W nan nan nan nan nan nan nan nan nan nan nan
123 GLOB YGL125W 46.4863 63.5449 56.8863 66.7322 57.2348 61.9736 44.6274 55.9456 50.1612 49.3058 44.6274
124 GLOB YBR145W 71.6811 72.2067 69.1387 66.9599 61.7845 69.9317 66.1771 78.3538 76.4543 76.689 61.7845
125 GLOB YJR109C 93.7173 102.889 104.636 81.3546 95.309 95.4597 91.9015 81.1718 101.141 111.183 81.1718
126 TM YGL140C nan nan nan nan nan nan nan nan nan nan nan
127 GLOB YOR222W 51.8782 53.6228 52.1708 44.0987 42.1839 50.2955 60.3832 55.3705 51.3427 59.3051 42.1839
128 GLOB YLR216C 50.672 47.3561 51.6084 55.7625 48.2695 53.6904 52.5112 52.7914 55.2405 49.0236 47.3561
129 GLOB YMR260C 95.1133 96.3577 95.4825 90.1372 87.082 87.3282 84.01 103.503 87.6973 92.1059 84.01
130 GLOB YPR080W 69.343 65.9511 62.5095 68.7091 74.1874 65.662 72.1282 67.9846 71.1639 80.6316 62.5095
131 GLOB YLR247C 467.015 479.043 480.562 480.91 467.606 465.965 451.618 471.889 493.547 459.555 451.618
132 GLOB YDR172W 533.134 883.615 707.849 529.659 603.805 634.76 466.633 582.616 503.112 522.806 466.633
133 GLOB YJL001W 41.4077 43.6905 41.8556 39.8563 40.154 35.9954 42.4686 39.982 38.3909 36.6323 35.9954
134 GLOB YER094C 30.1161 28.0345 29.3946 33.7053 32.8441 37.4113 35.4892 33.2834 35.04 33.5667 28.0345
135 GLOB YPR131C 85.4278 83.7639 84.9304 86.0783 82.5741 90.7966 80.5847 83.9952 84.1574 81.8579 80.5847
136 GLOB YHL034C 291.382 262.788 312.317 222.989 396.842 262.993 203.216 441.75 345.174 238.927 203.216
137 GLOB YJL063C 41.903 41.2901 46.07 48.4176 45.4849 44.2953 48.2377 47.5876 41.5408 41.9055 41.2901
138 GLOB YDR237W 131.318 128.731 128.04 123.624 126.623 127.599 120.784 135.013 130.732 133.417 120.784
139 nan YJR145C;YHR203C nan nan nan nan nan nan nan nan nan nan nan
140 GLOB YJL096W 80.2118 81.2893 81.4025 76.6961 81.7144 81.4081 80.7386 83.4759 85.0474 82.5601 76.6961
141 GLOB YKL170W 47.0899 48.1969 49.5655 49.5811 43.2717 47.6726 42.9156 45.5745 43.025 48.1392 42.9156
142 GLOB YKL138C 58.5726 59.9552 60.8159 61.653 54.8818 59.8551 54.9758 61.5475 55.2471 51.2184 51.2184
143 GLOB YKR085C 118.672 112.583 124.472 126.38 119.537 115.716 116.425 121.473 111.813 118.699 111.813
144 GLOB YKR006C 156.35 163.603 155.192 152.136 166.211 289.602 170.911 202.862 155.881 156.107 152.136
145 GLOB YML009C 29.8286 25.8072 27.939 30.6258 27.2023 30.3962 28.6167 25.8633 28.2432 28.2663 25.8072
146 GLOB YLR196W 244.557 244.475 261.676 236.052 244.674 241.911 247.99 249.161 246.978 247.769 236.052
147 GLOB YMR024W 150.871 141.689 152.756 145.788 200.446 145.367 153.847 163.583 146.533 155.793 141.689
148 GLOB YML025C 124.695 124.34 120.557 119.953 124.606 122.898 129.548 122.235 134.24 124.378 119.953
149 GLOB YNL005C 180.405 161.146 168.116 176.019 169.738 178.474 173.568 164.744 170.221 160.319 160.319
150 GLOB YMR286W 20.1995 19.8886 20.6032 23.4665 21.348 20.4719 20.0747 20.2156 20.6032 20.6032 19.8886
151 GLOB YNL252C 122.246 123.696 121.188 126.072 117.987 123.679 117.97 124.38 123.141 115.234 115.234
152 GLOB YNL177C 174.28 167.275 162.571 173.631 173.712 163.839 188.547 230.328 164.705 164.781 162.571
153 GLOB YNR022C 68.4298 64.1923 63.6856 65.3318 68.6081 63.8874 63.7501 62.6123 64.3169 67.7163 62.6123
154 GLOB YNL284C 265.076 344.011 203.458 205.579 285.895 298.676 494.572 306.155 276.515 284.315 203.458
155 GLOB YOR017W 307.359 381.491 298.752 380.386 285.64 308.754 283.967 319.147 442.549 311.072 283.967
156 GLOB YOL041C 341.618 487.867 300.919 290.915 288.125 292.441 288.552 277.02 488.144 293.324 277.02
157 GLOB YPL173W 210.81 364.905 225.695 183.044 191.496 254.033 306.705 276.77 219.696 262.165 183.044
158 GLOB YOR150W 59.7049 62.5247 62.2029 55.6442 58.8848 50.1503 58.3034 57.6323 62.8229 61.5425 50.1503
159 GLOB YER165W 381.12 391.446 427.684 388.801 380.16 241.155 383.403 391.888 378.556 228.197 228.197
160 GLOB YGL049C 1428.16 2490.87 2435.13 1902.14 2249.82 1433.93 1612.13 1879.52 2651.64 1805.21 1428.16
161 GLOB YGR162W 2604.7 2093.55 1693.96 1384.6 1350.0 2134.79 1330.35 1324.05 1894.91 2011.89 1324.05
162 GLOB YGL094C 375.785 419.404 699.628 1187.48 375.596 376.641 590.043 437.541 588.073 575.602 375.596
163 TM YJL186W nan nan nan nan nan nan nan nan nan nan nan
164 SP+TM YJL002C nan nan nan nan nan nan nan nan nan nan nan
165 GLOB YMR193W 93.5175 91.5007 95.7341 84.4511 88.6608 92.8629 89.3102 86.995 88.6778 95.2217 84.4511
166 GLOB YKL025C 689.067 554.911 544.562 715.763 529.854 369.114 345.375 507.991 491.491 527.446 345.375
167 GLOB YGR076C 56.6155 60.0328 59.8122 64.3798 56.7105 67.0976 67.7168 57.5552 62.9362 63.5675 56.6155
168 GLOB YGL068W 221.117 154.992 197.521 220.704 253.575 303.06 233.995 234.255 163.1 167.043 154.992
169 GLOB YGR220C 137.269 138.604 154.59 128.616 138.465 145.129 142.345 136.266 144.587 148.914 128.616
170 GLOB YMR098C 228.692 226.406 212.644 296.771 290.534 221.175 210.379 308.326 262.391 219.391 210.379
171 GLOB YNL185C 42.3718 37.4495 35.4262 41.4123 36.2232 33.1467 33.9501 38.2438 36.308 41.3645 33.1467
172 GLOB YBR082C 12.0585 14.6898 18.1168 9.0823 15.876 16.1609 13.9507 8.93521 10.215 9.49288 8.93521
173 GLOB YDR214W 98.287 93.1375 98.8481 98.4282 101.29 102.004 100.617 100.231 92.894 97.7497 92.894
174 GLOB YCR093W 351.671 356.603 345.859 342.469 371.834 646.977 328.487 352.296 339.978 341.096 328.487
175 GLOB YER168C 49.4905 59.0474 63.4521 52.9481 59.0257 64.8821 65.8779 41.4971 55.2597 59.2328 41.4971
176 GLOB YER068W 872.544 1288.59 875.779 782.341 874.633 1019.32 1124.21 769.089 1179.68 1565.8 769.089
177 GLOB YMR235C 84.263 84.3807 94.854 92.9636 95.8507 84.2818 92.6166 97.9192 89.4085 96.5106 84.263
178 GLOB YKL010C 992.583 1028.52 5899.52 904.065 814.194 910.132 518.556 733.033 1007.58 526.189 518.556
179 GLOB YKR059W 48.7675 48.5443 44.21 50.6832 48.3488 40.3619 47.8813 42.9071 51.1153 45.7931 40.3619
180 GLOB YJL138C 46.9506 46.1833 55.6152 46.076 50.7037 50.0152 42.3492 43.6294 40.2565 52.2741 40.2565
181 GLOB YDL084W 148.333 135.214 145.864 112.688 129.319 130.523 142.508 126.775 130.0 138.591 112.688
182 GLOB YDL140C 1578.71 3217.32 1680.99 4536.84 4037.22 2230.14 1433.29 3022.44 1493.75 1606.15 1433.29
183 GLOB YOR046C 160.844 167.053 180.131 151.455 141.934 150.287 291.582 151.386 166.797 158.735 141.934
184 GLOB YKL190W 41.714 47.3553 50.8894 44.7294 44.4764 42.1386 48.4443 42.5455 54.4 40.7374 40.7374
185 GLOB YBR022W 21.6887 22.3418 16.7153 17.3346 19.1652 14.5962 17.4632 19.5384 18.8455 19.4644 14.5962
186 GLOB YBR017C 17.5309 17.3486 12.4358 10.0312 17.741 22.6001 22.9077 4.34865 12.5018 33.5933 4.34865
187 GLOB YBR080C 330.892 329.354 327.237 331.861 329.516 326.479 330.121 329.496 331.057 326.34 326.34
188 GLOB YBR214W 467.153 377.031 410.767 346.644 399.384 363.646 621.761 586.69 439.25 539.662 346.644
189 GLOB YBR143C 94.2112 96.6238 96.1078 106.213 95.5022 87.5966 84.773 82.9987 98.0632 94.578 82.9987
190 GLOB YDL160C 120.548 124.321 141.406 128.455 136.829 126.549 118.666 117.318 121.228 119.012 117.318
191 GLOB YDL022W 45.9919 51.1786 57.9889 49.6876 55.0876 54.7631 61.6221 58.9888 48.707 53.6095 45.9919
192 GLOB YDL192W 27.07 28.981 33.2428 30.8493 23.9318 26.3847 33.0942 31.2318 42.665 25.3433 23.9318
193 GLOB YDR408C 3.02581 4.34048 3.64235 5.57823 5.24037 6.13826 11.1046 11.1875 8.5319 10.0963 3.02581
194 GLOB YDR341C 17.2578 13.4033 17.5788 18.8595 31.62 16.1828 13.7731 23.2002 13.7661 26.9203 13.4033
195 GLOB YER086W 120.305 113.888 125.544 118.796 125.093 113.583 123.115 120.966 111.703 120.369 111.703
196 GLOB YGR173W 89.9008 85.2514 78.1446 77.5104 76.2128 89.2878 93.9896 87.8829 82.5664 83.2881 76.2128
197 GLOB YFL037W 95.1506 89.3959 91.7613 91.9426 100.119 84.1049 98.7777 87.972 82.2547 87.3918 82.2547
198 GLOB YHL011C 42.6358 46.8691 46.8389 47.2915 53.6699 50.1418 48.4123 56.0977 45.9937 46.1143 42.6358
199 GLOB YGR175C 44.491 37.604 46.1292 49.7832 41.5092 41.6125 42.385 38.1757 41.7242 33.4785 33.4785
200 GLOB YIL094C 49.2102 56.7129 43.9162 61.6849 55.2533 43.4646 47.8047 45.2613 48.3956 54.1956 43.4646
201 GLOB YKL196C 30.3959 30.5621 25.3911 31.377 29.6238 31.508 34.5942 23.9515 28.9026 27.4682 23.9515
202 GLOB YJR072C 215.853 144.737 128.059 178.618 138.179 195.137 136.241 183.86 225.945 132.477 128.059
203 GLOB YKR080W 38.4073 28.9353 31.9309 32.4288 25.5997 34.0206 34.0357 29.6546 35.975 29.5617 25.5997
204 GLOB YLR113W 112.159 110.153 98.0023 115.541 118.433 111.7 110.838 120.896 100.041 113.705 98.0023
205 GLOB YLL026W 176.894 155.889 155.139 164.118 145.64 149.166 149.316 172.851 145.43 163.821 145.43

In [83]:
df[df["node"] == "YBR014C"]["final_sequence"]

917    SVNESITTHHPDSLVTFDNSGNAPGTHQSVHDTVNTQDKEAEEVDK...
Name: final_sequence, dtype: object

In [80]:
df[df["node"] == "YBR014C"]["final_structure_source"]

917    AF2-cleaved
Name: final_structure_source, dtype: object

In [75]:
df.columns

Index(['node', '_wkshell', 'degree_centrality', 'betweenness_centrality',
       'eigenvector_centrality', 'closeness_centrality', 'load_centrality',
       'pagerank', 'information_centrality', 'CentralityCosDist_rank',
       'CentralityCosDist_similarity_score', 'has_verified_sequence',
       'sequence', 'UniProtKB-AC', 'DeepTMHMM_trimmed_sequence',
       'DeepTMHMM_class', 'cleavage_site_start', 'signalP_trimmed_sequence',
       'ProteinName', 'GO_terms', 'GO_terms_human_readable',
       'localization_keywords', 'parsed_functions', 'parsed_PTMs',
       'ptm_bronze', 'ptm_gold', 'ptm_silver', 'IDR_count', 'IDR_sequences',
       'IDR_ranges', 'N_aa_disordered', 'disorder_fraction',
       'is_disordered_0.05', 'is_disordered_0.10', 'is_disordered_0.15',
       'is_disordered_0.20', 'is_disordered_0.25', 'is_disordered_0.30',
       'is_disordered_0.35', 'is_disordered_0.40', 'is_disordered_0.45',
       'is_disordered_0.50', 'is_disordered_0.55', 'is_disordered_0.60',
       'is_disordered_0.65', 'is_disordered_0.70', 'is_disordered_0.75',
       'is_disordered_0.80', 'is_disordered_0.85', 'is_disordered_0.90',
       'is_disordered_0.95', 'is_disordered_1.00', 'albatross', 'cider',
       'structure_path', 'structure_exists', 'structure_fasta_path',
       'structure_sequence', 'cleaved_structure_path',
       'cleaved_structure_sequence', 'sequence_matches_structure',
       'final_structure_path', 'final_sequence', 'final_structure_source',
       'mean_plddt', 'L', 'dH', 'dCp', 'dS', 'Ghosh-Dill-dG', 'cagiada-dG',
       'Rosetta_total_score_0001', 'Rosetta_total_score_0002',
       'Rosetta_total_score_0003', 'Rosetta_total_score_0004',
       'Rosetta_total_score_0005', 'Rosetta_total_score_0006',
       'Rosetta_total_score_0007', 'Rosetta_total_score_0008',
       'Rosetta_total_score_0009', 'Rosetta_total_score_0010',
       'Rosetta_best_total_score', 'Rosetta_best_pose_index',
       'Rosetta_best_score_file', 'Rosetta_n_found', 'FoldX_total_energy_0001',
       'FoldX_total_energy_0002', 'FoldX_total_energy_0003',
       'FoldX_total_energy_0004', 'FoldX_total_energy_0005',
       'FoldX_total_energy_0006', 'FoldX_total_energy_0007',
       'FoldX_total_energy_0008', 'FoldX_total_energy_0009',
       'FoldX_total_energy_0010', 'FoldX_best_total_energy',
       'FoldX_best_pose_index', 'FoldX_best_file', 'FoldX_n_found'],
      dtype='object')

In [87]:
df = pd.read_pickle("../8-protein-half-life/processed-data/0-s288c-step8.pkl")

In [88]:
list(df.columns)

['node',
 '_wkshell',
 'degree_centrality',
 'betweenness_centrality',
 'eigenvector_centrality',
 'closeness_centrality',
 'load_centrality',
 'pagerank',
 'information_centrality',
 'CentralityCosDist_rank',
 'CentralityCosDist_similarity_score',
 'has_verified_sequence',
 'sequence',
 'UniProtKB-AC',
 'DeepTMHMM_trimmed_sequence',
 'DeepTMHMM_class',
 'cleavage_site_start',
 'signalP_trimmed_sequence',
 'ProteinName',
 'GO_terms',
 'GO_terms_human_readable',
 'localization_keywords',
 'parsed_functions',
 'parsed_PTMs',
 'ptm_bronze',
 'ptm_gold',
 'ptm_silver',
 'IDR_count',
 'IDR_sequences',
 'IDR_ranges',
 'N_aa_disordered',
 'disorder_fraction',
 'is_disordered_0.05',
 'is_disordered_0.10',
 'is_disordered_0.15',
 'is_disordered_0.20',
 'is_disordered_0.25',
 'is_disordered_0.30',
 'is_disordered_0.35',
 'is_disordered_0.40',
 'is_disordered_0.45',
 'is_disordered_0.50',
 'is_disordered_0.55',
 'is_disordered_0.60',
 'is_disordered_0.65',
 'is_disordered_0.70',
 'is_disordered_0.75',
 'is_disordered_0.80',
 'is_disordered_0.85',
 'is_disordered_0.90',
 'is_disordered_0.95',
 'is_disordered_1.00',
 'albatross',
 'cider',
 'structure_path',
 'structure_exists',
 'structure_fasta_path',
 'structure_sequence',
 'cleaved_structure_path',
 'cleaved_structure_sequence',
 'sequence_matches_structure',
 'final_structure_path',
 'final_sequence',
 'final_structure_source',
 'mean_plddt',
 'L',
 'dH',
 'dCp',
 'dS',
 'Ghosh-Dill-dG',
 'cagiada-dG',
 'Rosetta_total_score_0001',
 'Rosetta_total_score_0002',
 'Rosetta_total_score_0003',
 'Rosetta_total_score_0004',
 'Rosetta_total_score_0005',
 'Rosetta_total_score_0006',
 'Rosetta_total_score_0007',
 'Rosetta_total_score_0008',
 'Rosetta_total_score_0009',
 'Rosetta_total_score_0010',
 'Rosetta_best_total_score',
 'Rosetta_best_pose_index',
 'Rosetta_best_score_file',
 'Rosetta_n_found',
 'FoldX_total_energy_0001',
 'FoldX_total_energy_0002',
 'FoldX_total_energy_0003',
 'FoldX_total_energy_0004',
 'FoldX_total_energy_0005',
 'FoldX_total_energy_0006',
 'FoldX_total_energy_0007',
 'FoldX_total_energy_0008',
 'FoldX_total_energy_0009',
 'FoldX_total_energy_0010',
 'FoldX_best_total_energy',
 'FoldX_best_pose_index',
 'FoldX_best_file',
 'FoldX_n_found',
 'Christiano_degradation_rate(min-1)',
 'Christiano_degradation_R2',
 'Christiano_halflife_min',
 'Villen_halflife_hours',
 'Villen_halflife_SD_hours',
 'Villen_halflife_CV',
 'Villen_halflife_min',
 'Villen_halflife_SD_min']

In [92]:
for index, row in df.iterrows():
    print(index, row["node"], row["DeepTMHMM_class"], row["Villen_halflife_hours"], row["Villen_halflife_SD_hours"], row["Villen_halflife_CV"])

0 YKL063C TM 2.37 0.18 0.07
1 YDL223C GLOB 4.25 2.07 0.49
2 YPL036W TM 2.0 0.0 0.0
3 YPL050C GLOB 1.78 0.02 0.01
4 YJR148W GLOB 3.68 0.37 0.1
5 YHR208W GLOB 1.8 0.1 0.05
6 YBR035C GLOB 2.97 0.05 0.02
7 YPR008W GLOB 1.84 0.09 0.05
8 YKL024C GLOB 1.74 0.07 0.04
9 YBR286W SP 2.5 0.06 0.03
10 YLR420W GLOB 1.85 0.0 0.0
11 YKR066C GLOB 2.26 0.02 0.01
12 YNL117W GLOB nan nan nan
13 YNL015W GLOB 5.41 0.01 0.0
14 YOR285W GLOB 3.55 0.06 0.02
15 YOR239W GLOB 1.97 0.05 0.02
16 YJL055W GLOB 3.4 0.1 0.03
17 YJL066C GLOB 4.14 0.17 0.04
18 YGR027W-A;YGR038C-A;YJR026W;YLR227W-A;YML040W nan nan nan nan
19 YGL087C GLOB 3.05 0.05 0.02
20 YNL134C GLOB 4.56 0.15 0.03
21 YNR034W-A GLOB 46.61 19.96 0.43
22 YPL111W GLOB 2.33 0.1 0.04
23 YIR037W GLOB 3.69 0.07 0.02
24 YML022W GLOB 1.23 0.0 0.0
25 YNL104C GLOB 2.51 0.09 0.03
26 YEL060C SP 6.55 0.8 0.12
27 YOR168W GLOB 1.7 0.02 0.01
28 YER175C GLOB 5.5 1.63 0.3
29 YEL071W GLOB 2.62 0.11 0.04
30 YBR222C GLOB 3.29 0.12 0.04
31 YOR323C GLOB 1.91 0.05 0.02
32 YBL037W GLOB 2.47 0.54 0.22
33 YOL062C GLOB nan nan nan
34 YJR005W GLOB 2.34 0.0 0.0
35 YLR352W GLOB nan nan nan
36 YNL059C GLOB 2.08 0.02 0.01
37 YBL024W GLOB 1.42 0.02 0.01
38 YDR356W GLOB 2.57 0.09 0.03
39 YBR149W GLOB 3.71 0.02 0.01
40 YDR037W GLOB 1.49 0.01 0.01
41 YLR421C GLOB 2.38 0.0 0.0
42 YFL048C SP+TM 2.32 0.05 0.02
43 YDR270W TM nan nan nan
44 YKL042W GLOB 2.6 0.06 0.02
45 YHR019C GLOB 1.7 0.04 0.02
46 YLL018C GLOB 2.03 0.04 0.02
47 YKL103C GLOB 8.17 2.27 0.28
48 YLR080W SP+TM nan nan nan
49 YLR072W TM 2.27 0.0 0.0
50 YNL225C GLOB 2.47 0.33 0.13
51 YLR250W SP 2.09 0.01 0.01
52 YOL158C TM nan nan nan
53 YNL231C GLOB nan nan nan
54 YOR373W GLOB 1.65 0.28 0.17
55 YPL124W GLOB 2.52 0.75 0.3
56 YDL201W GLOB 1.18 0.0 0.0
57 YDL195W GLOB 2.49 0.09 0.04
58 YDR091C GLOB 1.42 0.04 0.03
59 YEL034W GLOB 1.63 0.04 0.02
60 YDR388W GLOB 3.02 0.28 0.09
61 YER007C-A GLOB 1.8 0.03 0.02
62 YEL065W TM nan nan nan
63 YER178W GLOB 2.77 0.06 0.02
64 YER048C GLOB 2.22 0.03 0.01
65 YGL245W GLOB 2.02 0.07 0.03
66 YFR009W GLOB 1.83 0.05 0.03
67 YHR020W GLOB 1.51 0.03 0.02
68 YJR014W GLOB 1.56 0.02 0.01
69 YNL247W GLOB 1.69 0.03 0.02
70 YLR244C GLOB 1.09 0.02 0.02
71 YOL111C GLOB 2.72 0.08 0.03
72 YOR187W GLOB 2.98 0.13 0.04
73 YPL048W GLOB 2.72 0.08 0.03
74 YPR163C GLOB 1.45 0.03 0.02
75 YDR406W TM 2.17 0.02 0.01
76 YMR058W SP+TM 2.52 0.34 0.14
77 YPR154W GLOB 3.04 0.05 0.02
78 YGR185C GLOB 1.72 0.01 0.01
79 YDL182W GLOB 3.44 0.11 0.03
80 YGR054W GLOB 1.74 0.03 0.02
81 YGR285C GLOB 1.52 0.02 0.01
82 YHR064C GLOB 1.53 0.02 0.01
83 YJR047C GLOB 3.55 0.86 0.24
84 YIL078W GLOB 1.7 0.06 0.03
85 YPL160W GLOB 1.76 0.05 0.03
86 YPR033C GLOB 1.72 0.07 0.04
87 YCL001W TM nan nan nan
88 YDL072C TM 3.27 0.03 0.01
89 YDL015C TM 2.41 0.05 0.02
90 YDR144C SP 1.05 0.14 0.13
91 YDR245W GLOB 1.88 0.0 0.0
92 YEL036C TM 2.28 0.14 0.06
93 YGL105W GLOB 1.95 0.05 0.02
94 YFR024C-A GLOB 3.12 0.11 0.04
95 YJL171C SP 3.57 0.15 0.04
96 YGL200C SP+TM 2.58 0.1 0.04
97 YKL065C TM 3.43 0.06 0.02
98 YKL165C TM 4.63 1.24 0.27
99 YLR386W GLOB 2.21 0.14 0.06
100 YML115C GLOB 1.73 0.03 0.02
101 YML067C TM 2.15 0.03 0.01
102 YNL121C GLOB 2.56 0.1 0.04
103 YMR008C SP nan nan nan
104 YOR153W TM 1.27 0.12 0.1
105 YOR016C SP+TM 2.29 0.05 0.02
106 YGR094W GLOB 1.62 0.03 0.02
107 YJL080C GLOB 2.29 0.1 0.05
108 YKL081W GLOB 1.5 0.06 0.04
109 YBR025C GLOB 1.89 0.06 0.03
110 YLR109W GLOB 1.71 0.11 0.06
111 YOL082W GLOB nan nan nan
112 YGL156W GLOB 23.45 16.81 0.72
113 YAL042W TM 1.94 0.08 0.04
114 YAL007C SP+TM 2.43 0.01 0.0
115 YBR187W SP+TM nan nan nan
116 YAR002C-A SP+TM 2.53 0.08 0.03
117 YGL167C TM 2.3 0.01 0.0
118 YBR205W TM 2.39 0.01 0.01
119 YHR034C GLOB 2.01 0.07 0.03
120 YMR038C GLOB 1.83 0.03 0.02
121 YNL208W GLOB 2.69 0.19 0.07
122 YBR096W TM 6.29 2.0 0.32
123 YGL125W GLOB 2.14 0.25 0.12
124 YBR145W GLOB 2.91 0.05 0.02
125 YJR109C GLOB 1.08 0.01 0.01
126 YGL140C TM 2.13 0.45 0.21
127 YOR222W GLOB 2.54 0.1 0.04
128 YLR216C GLOB 2.55 0.0 0.0
129 YMR260C GLOB 1.51 0.05 0.03
130 YPR080W GLOB nan nan nan
131 YLR247C GLOB nan nan nan
132 YDR172W GLOB 1.54 0.02 0.02
133 YJL001W GLOB 2.65 0.08 0.03
134 YER094C GLOB 2.38 0.07 0.03
135 YPR131C GLOB 14.29 10.02 0.7
136 YHL034C GLOB 3.0 0.07 0.02
137 YJL063C GLOB 2.5 0.12 0.05
138 YDR237W GLOB 3.34 0.87 0.26
139 YJR145C;YHR203C nan 1.48 0.06 0.04
140 YJL096W GLOB 2.64 0.3 0.12
141 YKL170W GLOB 2.86 0.14 0.05
142 YKL138C GLOB nan nan nan
143 YKR085C GLOB 2.18 0.11 0.05
144 YKR006C GLOB 2.44 0.03 0.01
145 YML009C GLOB nan nan nan
146 YLR196W GLOB 1.07 0.03 0.02
147 YMR024W GLOB 2.69 0.03 0.01
148 YML025C GLOB 2.59 0.15 0.06
149 YNL005C GLOB 2.5 0.18 0.07
150 YMR286W GLOB 1.97 0.15 0.08
151 YNL252C GLOB 2.62 0.23 0.09
152 YNL177C GLOB nan nan nan
153 YNR022C GLOB 2.21 0.11 0.05
154 YNL284C GLOB 3.18 0.0 0.0
155 YOR017W GLOB nan nan nan
156 YOL041C GLOB 1.06 0.02 0.02
157 YPL173W GLOB 2.64 0.21 0.08
158 YOR150W GLOB 2.41 0.17 0.07
159 YER165W GLOB 1.45 0.03 0.02
160 YGL049C GLOB 2.54 0.03 0.01
161 YGR162W GLOB 1.37 0.03 0.02
162 YGL094C GLOB 1.92 0.1 0.05
163 YJL186W TM 1.7 0.12 0.07
164 YJL002C SP+TM 2.4 0.02 0.01
165 YMR193W GLOB 2.43 0.08 0.03
166 YKL025C GLOB 1.75 0.04 0.02
167 YGR076C GLOB 3.94 1.4 0.35
168 YGL068W GLOB 2.88 0.12 0.04
169 YGR220C GLOB 2.38 0.19 0.08
170 YMR098C GLOB nan nan nan
171 YNL185C GLOB 2.44 0.18 0.07
172 YBR082C GLOB 2.68 0.02 0.01
173 YDR214W GLOB 2.8 0.07 0.02
174 YCR093W GLOB 2.01 0.12 0.06
175 YER168C GLOB 2.65 0.11 0.04
176 YER068W GLOB 1.89 0.08 0.04
177 YMR235C GLOB 1.79 0.02 0.01
178 YKL010C GLOB 2.72 0.82 0.3
179 YKR059W GLOB nan nan nan
180 YJL138C GLOB nan nan nan
181 YDL084W GLOB 2.18 0.05 0.02
182 YDL140C GLOB 1.69 0.0 0.0
183 YOR046C GLOB 1.86 0.01 0.0
184 YKL190W GLOB 2.45 0.19 0.08
185 YBR022W GLOB nan nan nan
186 YBR017C GLOB 2.12 0.09 0.04
187 YBR080C GLOB 2.56 0.08 0.03
188 YBR214W GLOB 155.93 0.0 0.0
189 YBR143C GLOB 1.54 0.02 0.02
190 YDL160C GLOB 2.52 0.06 0.02
191 YDL022W GLOB 4.51 0.1 0.02
192 YDL192W GLOB nan nan nan
193 YDR408C GLOB 5.86 3.04 0.52
194 YDR341C GLOB 1.54 0.01 0.0
195 YER086W GLOB 1.86 0.06 0.03
196 YGR173W GLOB 1.35 0.01 0.0
197 YFL037W GLOB 2.72 0.15 0.06
198 YHL011C GLOB 1.3 0.01 0.01
199 YGR175C GLOB 0.98 0.04 0.05
200 YIL094C GLOB 4.06 0.14 0.03
201 YKL196C GLOB 2.09 0.0 0.0
202 YJR072C GLOB 1.22 0.0 0.0
203 YKR080W GLOB 3.86 0.1 0.03
204 YLR113W GLOB 2.73 0.12 0.05
205 YLL026W GLOB 4.48 0.04 0.01
206 YLR270W GLOB 4.33 0.09 0.02
207 YLR180W GLOB 1.45 0.03 0.02
208 YMR186W GLOB 2.57 0.06 0.02
209 YNL129W GLOB 2.15 0.24 0.11
210 YNL016W GLOB 2.09 0.08 0.04
211 YPL010W GLOB 2.58 0.11 0.04
212 YNL307C GLOB 2.4 0.11 0.05
213 YPL240C GLOB 3.21 0.02 0.01
214 YPL218W GLOB 2.57 0.09 0.03
215 YOL142W GLOB 1.08 0.08 0.07
216 YHR103W GLOB 0.83 0.0 0.0
217 YER073W GLOB 1.46 0.02 0.01
218 YJR024C GLOB 1.82 0.03 0.02
219 YLR089C GLOB 2.56 0.12 0.05
220 YKL120W TM nan nan nan
221 YMR108W GLOB 1.41 0.01 0.01
222 YOL096C GLOB nan nan nan
223 YOR136W GLOB 4.01 0.02 0.0
224 YKL126W GLOB 2.85 0.06 0.02
225 YNL064C GLOB 1.62 0.0 0.0
226 YPL225W GLOB 2.51 0.07 0.03
227 YDL190C GLOB 2.67 0.08 0.03
228 YEL022W GLOB 2.36 0.06 0.02
229 YDR129C GLOB 2.85 0.01 0.0
230 YGR218W GLOB 2.39 0.03 0.01
231 YIL156W-B SP nan nan nan
232 YLR268W TM 2.62 0.09 0.03
233 YJR077C GLOB 1.96 0.07 0.04
234 YMR145C GLOB 1.68 0.03 0.02
235 YOR075W TM 1.77 0.34 0.19
236 YPL063W GLOB 2.01 0.05 0.02
237 YBR122C GLOB 2.01 0.47 0.23
238 YBL038W GLOB 3.06 0.45 0.15
239 YDR041W GLOB 2.3 0.24 0.1
240 YCR071C GLOB 2.72 0.21 0.08
241 YDR116C GLOB 2.67 0.4 0.15
242 YDR322W GLOB 2.65 0.1 0.04
243 YDR296W GLOB 2.51 0.15 0.06
244 YEL050C GLOB 3.14 0.0 0.0
245 YDR462W GLOB 2.8 0.4 0.14
246 YLR312W-A GLOB 2.38 0.28 0.12
247 YNL047C GLOB nan nan nan
248 YNR039C TM nan nan nan
249 YFR033C GLOB 3.19 0.01 0.0
250 Q0250 TM 2.01 0.22 0.11
251 YLR298C GLOB nan nan nan
252 YGL191W TM 1.77 0.11 0.06
253 YGL187C GLOB 2.44 0.09 0.04
254 YHR001W-A TM 2.64 0.16 0.06
255 YGR132C TM 3.11 0.08 0.03
256 YIL111W TM 3.06 0.16 0.05
257 YHR051W GLOB 2.77 0.11 0.04
258 YKR016W GLOB 2.89 0.09 0.03
259 YJL166W TM 3.39 0.0 0.0
260 YLR356W TM 6.11 2.4 0.39
261 YLR038C GLOB 3.04 0.04 0.01
262 YNL052W TM 0.84 0.27 0.32
263 YMR089C TM 2.39 0.04 0.01
264 YNR018W TM 1.11 0.16 0.15
265 YNL055C GLOB 3.75 0.09 0.02
266 YPR191W GLOB 3.14 0.02 0.01
267 YOR065W TM 3.76 0.24 0.06
268 YDR529C GLOB 3.36 0.21 0.06
269 YCL057C-A TM 2.82 0.39 0.14
270 YEL024W GLOB 3.07 0.12 0.04
271 YDL067C TM 1.63 0.07 0.04
272 YGR012W GLOB 3.18 0.42 0.13
273 YGR231C TM 3.09 0.06 0.02
274 YHR003C GLOB 1.99 0.17 0.09
275 YJL207C GLOB 2.42 0.64 0.26
276 YMR203W GLOB 2.53 0.09 0.04
277 YER017C TM 2.78 0.05 0.02
278 YBL030C TM nan nan nan
279 YPL078C TM 2.69 0.02 0.01
280 YKL016C GLOB 2.65 0.06 0.02
281 Q0045 TM 2.28 0.14 0.06
282 YOR271C TM 1.52 0.04 0.02
283 YBR039W GLOB 2.96 0.09 0.03
284 Q0085 TM 2.91 0.0 0.0
285 YDL004W GLOB 2.85 0.1 0.03
286 YDR298C GLOB 2.64 0.0 0.0
287 YDL181W GLOB 2.07 0.86 0.41
288 YDR322C-A GLOB 2.36 0.1 0.04
289 YFR011C GLOB 2.63 0.12 0.04
290 YJR121W GLOB 2.95 0.09 0.03
291 YKR049C GLOB 3.49 0.02 0.01
292 YLR295C GLOB 2.62 0.05 0.02
293 YML081C-A TM 2.57 0.06 0.02
294 YMR003W TM nan nan nan
295 YNL131W TM 2.39 0.26 0.11
296 YOL077W-A GLOB 1.9 0.05 0.03
297 YPR020W TM 2.57 0.0 0.0
298 YPL271W GLOB 2.7 0.27 0.1
299 YDL174C GLOB 2.08 0.0 0.0
300 YHR079C SP+TM nan nan nan
301 YIL077C TM nan nan nan
302 YLR090W GLOB nan nan nan
303 YAL010C GLOB nan nan nan
304 YER154W TM nan nan nan
305 YKL027W GLOB 1.66 0.03 0.02
306 YDR430C GLOB 2.26 0.03 0.01
307 YHR147C GLOB 2.3 0.21 0.09
308 YGR207C GLOB 3.01 0.11 0.04
309 YJR080C GLOB 4.61 2.37 0.51
310 YJR045C GLOB nan nan nan
311 YLR355C GLOB 1.64 0.02 0.01
312 YMR083W GLOB 2.9 0.07 0.02
313 YOR125C GLOB 5.16 0.0 0.0
314 YMR241W GLOB 2.64 0.12 0.05
315 YLR259C GLOB 3.02 0.12 0.04
316 YCL044C GLOB 2.11 0.03 0.02
317 YGL153W GLOB 2.37 0.05 0.02
318 YKL148C GLOB 3.48 0.01 0.0
319 YIL125W GLOB 3.16 0.08 0.03
320 YLL041C GLOB 3.21 0.01 0.0
321 YPL132W TM nan nan nan
322 YDR075W GLOB 2.51 0.0 0.0
323 YNL201C GLOB 1.86 0.05 0.02
324 YOR390W;YPL279C nan nan nan nan
325 YBL046W GLOB 1.81 0.0 0.0
326 YBL047C GLOB 3.02 0.08 0.03
327 YCR030C GLOB 3.29 0.06 0.02
328 YHR047C GLOB 2.4 0.07 0.03
329 YBL051C GLOB 2.41 0.26 0.11
330 YLR064W TM nan nan nan
331 YBL055C GLOB 1.49 0.04 0.03
332 YMR198W GLOB nan nan nan
333 YDR207C GLOB 1.27 0.0 0.0
334 YNL007C GLOB 2.9 0.02 0.01
335 YPR018W GLOB 1.53 0.0 0.0
336 YNL091W GLOB 1.55 0.06 0.04
337 YBL056W GLOB 2.63 0.03 0.01
338 YGL210W GLOB 2.35 0.17 0.07
339 YDR071C GLOB 2.18 0.02 0.01
340 YGR205W GLOB 45.92 21.71 0.47
341 YBL057C GLOB 2.28 0.08 0.03
342 YDL126C GLOB 2.82 0.06 0.02
343 YBR273C GLOB 2.3 0.01 0.0
344 YBR179C GLOB 5.04 0.0 0.0
345 YDL091C GLOB nan nan nan
346 YBR280C GLOB 3.69 0.0 0.0
347 YDR049W GLOB 1.59 0.07 0.04
348 YDL132W GLOB 2.37 0.14 0.06
349 YDR328C GLOB 2.66 0.05 0.02
350 YDR057W SP 2.06 0.05 0.02
351 YER065C GLOB nan nan nan
352 YDR330W GLOB 2.93 0.18 0.06
353 YFL044C GLOB 2.34 0.58 0.25
354 YER100W TM 0.83 0.01 0.01
355 YGR048W GLOB 2.45 0.05 0.02
356 YIL030C TM 5.88 0.0 0.0
357 YGR119C GLOB 1.9 0.02 0.01
358 YJR092W GLOB 2.15 0.31 0.14
359 YJR090C GLOB nan nan nan
360 YLL039C;YLR167W nan nan nan nan
361 YKL100C TM 2.36 0.0 0.0
362 YLR207W SP+TM nan nan nan
363 YLR088W TM nan nan nan
364 YML029W TM 2.24 0.1 0.04
365 YML013W GLOB nan nan nan
366 YMR067C GLOB 2.32 0.09 0.04
367 YML088W GLOB nan nan nan
368 YMR119W TM nan nan nan
369 YNL141W GLOB 0.65 0.01 0.01
370 YNL085W GLOB 0.51 0.02 0.04
371 YOR375C GLOB 3.93 0.07 0.02
372 YOL013C TM nan nan nan
373 YOR157C GLOB 2.46 0.04 0.02
374 YBL058W GLOB 2.7 0.08 0.03
375 YBR170C GLOB 2.3 0.01 0.0
376 YBR056W GLOB 4.42 1.0 0.23
377 YHR132W-A GLOB 43.38 0.0 0.0
378 YOR048C GLOB 1.45 0.04 0.03
379 YBL059C-A GLOB 2.45 0.2 0.08
380 YBL063W GLOB nan nan nan
381 YBL036C GLOB 1.69 0.0 0.0
382 YDR036C GLOB 2.3 0.25 0.11
383 YER136W GLOB 2.4 0.01 0.0
384 YDR304C SP 2.84 0.06 0.02
385 YBL060W GLOB nan nan nan
386 YBL064C GLOB 4.36 0.17 0.04
387 YPL059W GLOB 2.49 0.13 0.05
388 YJR016C GLOB 1.53 0.05 0.03
389 YOR108W GLOB 1.86 0.03 0.02
390 YER080W GLOB 2.86 0.06 0.02
391 YER170W GLOB nan nan nan
392 YML107C GLOB nan nan nan
393 YAL044W-A GLOB 1.53 0.06 0.04
394 YGR244C GLOB 3.89 0.23 0.06
395 YAL046C GLOB 2.05 0.0 0.0
396 YDR148C GLOB 3.55 0.07 0.02
397 YGR193C GLOB 2.73 0.03 0.01
398 YHL021C GLOB 9.14 3.55 0.39
399 YKL085W GLOB 3.9 0.12 0.03
400 YLR304C GLOB 3.34 0.09 0.03
401 YNL071W GLOB 3.08 0.07 0.02
402 YOR232W GLOB 2.5 0.1 0.04
403 YPR004C GLOB 3.42 0.38 0.11
404 YBL068W GLOB 1.34 0.0 0.0
405 YOL061W GLOB 1.57 0.01 0.01
406 YBL067C GLOB 1.7 0.01 0.0
407 YBL071W-A GLOB nan nan nan
408 YAL020C GLOB nan nan nan
409 YGR200C GLOB 1.33 0.03 0.02
410 YER055C GLOB 2.35 0.02 0.01
411 YKL110C GLOB nan nan nan
412 YIL103W GLOB 1.29 0.12 0.09
413 YLR384C GLOB 1.33 0.05 0.03
414 YKL191W GLOB 1.09 0.23 0.21
415 YPL086C GLOB 1.21 0.07 0.05
416 YBL072C GLOB nan nan nan
417 YBR084W GLOB 1.28 0.03 0.03
418 YBL072C;YER102W nan nan nan nan
419 YCR031C GLOB 1.52 0.06 0.04
420 YBR189W GLOB 1.5 0.05 0.04
421 YDL040C GLOB 2.14 0.1 0.05
422 YCR047C GLOB 1.08 0.11 0.1
423 YDR025W;YBR048W nan 1.53 0.06 0.04
424 YDL060W GLOB 1.17 0.01 0.01
425 YDR117C GLOB 2.3 0.05 0.02
426 YDR064W GLOB 1.49 0.05 0.03
427 YER074W;YIL069C nan nan nan nan
428 YDR450W;YML026C nan nan nan nan
429 YGR027C GLOB 1.5 0.06 0.04
430 YGL123W GLOB 1.53 0.06 0.04
431 YGR214W GLOB 1.52 0.06 0.04
432 YGR118W;YPR132W nan nan nan nan
433 YHL015W GLOB 1.53 0.06 0.04
434 YHL013C GLOB 1.49 0.01 0.01
435 YJL136C GLOB nan nan nan
436 YHR013C GLOB 1.9 0.05 0.02
437 YJR123W GLOB 1.52 0.06 0.04
438 YJL190C;YLR367W nan nan nan nan
439 YKL156W;YHR021C nan nan nan nan
440 YLR048W GLOB 1.42 0.07 0.05
441 YKR057W GLOB nan nan nan
442 YLR287C-A;YOR182C nan nan nan nan
443 YLR150W GLOB 1.63 0.07 0.04
444 YLR419W GLOB 1.6 0.02 0.01
445 YLR388W GLOB 1.54 0.07 0.04
446 YML024W;YDR447C nan 1.52 0.05 0.03
447 YLR441C GLOB 1.55 0.08 0.05
448 YMR116C GLOB 1.5 0.06 0.04
449 YML063W GLOB 1.52 0.06 0.04
450 YMR143W;YDL083C nan 1.49 0.05 0.04
451 YNL112W GLOB 0.83 0.05 0.06
452 YNL096C GLOB 1.49 0.06 0.04
453 YNL207W GLOB 1.15 0.0 0.0
454 YNL178W GLOB 1.5 0.05 0.04
455 YOL040C GLOB 1.52 0.06 0.04
456 YNL302C GLOB 1.51 0.05 0.03
457 YOR096W GLOB 1.52 0.05 0.04
458 YOL121C GLOB 1.59 0.07 0.04
459 YOR198C GLOB 2.41 0.1 0.04
460 YOR119C GLOB 0.93 0.06 0.06
461 YPL090C;YBR181C nan 1.53 0.07 0.04
462 YOR369C GLOB 1.52 0.06 0.04
463 YOR133W GLOB nan nan nan
464 YKR038C GLOB 1.76 0.01 0.0
465 YDL075W GLOB 1.52 0.07 0.04
466 YJL191W GLOB 1.41 0.2 0.14
467 YIL161W GLOB nan nan nan
468 YLR260W GLOB 2.36 0.23 0.1
469 YNL073W GLOB nan nan nan
470 YNL023C GLOB 5.18 0.53 0.1
471 YOR253W GLOB 1.97 0.17 0.08
472 YER131W GLOB 1.47 0.07 0.05
473 YKL032C GLOB 1.93 0.0 0.0
474 YLR264W GLOB 1.65 0.0 0.0
475 YNL050C GLOB 1.17 0.03 0.02
476 YOL080C GLOB 0.79 0.02 0.03
477 YPL032C GLOB 2.26 0.08 0.03
478 YDL061C GLOB 1.49 0.06 0.04
479 YPL081W GLOB 2.08 0.1 0.05
480 YKL143W GLOB 0.92 0.03 0.03
481 YNR046W GLOB 1.17 0.01 0.01
482 YNL224C GLOB 1.69 0.1 0.06
483 YGR081C GLOB 1.38 0.13 0.09
484 YLR398C GLOB 2.03 0.06 0.03
485 YNL314W GLOB nan nan nan
486 YPL204W GLOB 2.01 0.17 0.08
487 YPL012W GLOB 0.9 0.01 0.01
488 YGL189C GLOB 1.57 0.07 0.04
489 YPL266W GLOB 1.01 0.04 0.04
490 YNR051C GLOB 2.03 0.11 0.06
491 YLR327C GLOB 0.53 0.24 0.45
492 YNL054W-B GLOB nan nan nan
493 YLR325C GLOB 1.54 0.07 0.04
494 YOR359W GLOB 1.46 0.0 0.0
495 YAL035W GLOB 1.54 0.03 0.02
496 YAL036C GLOB 1.05 0.01 0.01
497 YBR263W GLOB 1.79 0.01 0.01
498 YDL053C GLOB 1.86 0.08 0.04
499 YDL051W GLOB 1.16 0.0 0.0
500 YDL213C GLOB 1.04 0.03 0.03
501 YDR381W GLOB 2.42 0.11 0.05
502 YDR412W GLOB 1.21 0.04 0.03
503 YER176W GLOB nan nan nan
504 YGL205W GLOB nan nan nan
505 YHL038C GLOB 1.51 0.45 0.3
506 YIL148W;YKR094C nan nan nan nan
507 YIL127C GLOB 0.87 0.08 0.09
508 YKL122C GLOB 1.81 0.05 0.03
509 YLR061W GLOB 1.48 0.06 0.04
510 YLR278C GLOB 2.21 0.0 0.0
511 YOR091W GLOB 1.03 0.02 0.02
512 YOR293W;YMR230W nan 1.49 0.05 0.04
513 YPL127C GLOB 2.39 0.08 0.03
514 YPL123C SP 19.45 14.55 0.75
515 YPL210C GLOB 1.95 0.01 0.01
516 YIL061C GLOB 0.87 0.0 0.0
517 YDR266C GLOB 1.59 0.05 0.03
518 YPL037C GLOB 1.83 0.05 0.03
519 YBL075C GLOB 2.93 1.72 0.59
520 YML078W GLOB 2.82 0.15 0.05
521 YBL074C GLOB 2.08 0.06 0.03
522 YKL173W GLOB 1.86 0.09 0.05
523 YHR165C GLOB 1.53 0.13 0.09
524 YKR018C GLOB 2.73 0.03 0.01
525 YLR347C GLOB 1.99 0.04 0.02
526 YBL076C GLOB 1.76 0.06 0.03
527 YDR035W GLOB 2.12 0.01 0.01
528 YHR087W GLOB 28.82 15.52 0.54
529 YNL137C GLOB 5.04 2.2 0.44
530 YDR050C GLOB 3.07 0.19 0.06
531 YBR196C GLOB 3.07 0.21 0.07
532 YPR074C GLOB 2.0 0.07 0.04
533 YFR053C GLOB 16.54 0.19 0.01
534 YGL117W GLOB nan nan nan
535 YBL098W GLOB 3.78 0.41 0.11
536 YGR138C TM 2.07 0.24 0.12
537 Q0140 GLOB 3.15 0.0 0.0
538 YDR494W GLOB 2.64 0.11 0.04
539 YBR146W GLOB 2.49 0.19 0.08
540 YGR150C GLOB 1.46 0.0 0.0
541 YER050C GLOB 2.07 0.16 0.08
542 YNL306W GLOB 2.28 0.21 0.09
543 YMR158W GLOB 2.77 0.41 0.15
544 YOR158W GLOB 2.71 0.2 0.07
545 YNR037C GLOB 2.6 0.09 0.03
546 YPL013C GLOB nan nan nan
547 YOR205C GLOB nan nan nan
548 YPR166C GLOB nan nan nan
549 YPL118W GLOB 2.73 0.21 0.08
550 YNR036C GLOB 2.72 0.0 0.0
551 YNL292W GLOB 1.47 0.02 0.02
552 YER105C GLOB 1.74 0.05 0.03
553 YGL092W GLOB 1.78 0.01 0.01
554 YFR002W GLOB 2.09 0.02 0.01
555 YKL057C GLOB 1.94 0.2 0.1
556 YLR018C TM 1.94 0.09 0.04
557 YKR082W GLOB 1.83 0.02 0.01
558 YML103C GLOB 1.75 0.05 0.03
559 YML031W TM 1.67 0.26 0.16
560 YMR153W GLOB 1.78 0.05 0.03
561 YMR129W TM 2.0 0.0 0.0
562 YHR024C GLOB 2.23 0.08 0.03
563 YLR163C GLOB 2.04 0.11 0.06
564 YJL041W GLOB 1.83 0.01 0.0
565 YBL079W GLOB 1.83 0.05 0.03
566 YDL116W GLOB 2.34 0.74 0.32
567 YJL008C GLOB 1.69 0.03 0.02
568 YAL026C TM 1.79 0.15 0.09
569 YJR042W GLOB 2.45 0.26 0.1
570 YLR208W GLOB 2.19 0.05 0.02
571 YPL169C GLOB 1.77 0.01 0.0
572 YGL172W GLOB 1.66 0.19 0.12
573 YJL061W GLOB 1.9 0.05 0.03
574 YBL080C GLOB nan nan nan
575 YDR061W GLOB nan nan nan
576 YMR293C GLOB nan nan nan
577 YBL084C GLOB nan nan nan
578 YDR260C GLOB nan nan nan
579 YDR118W GLOB nan nan nan
580 YGL240W GLOB nan nan nan
581 YFR036W GLOB nan nan nan
582 YIR025W GLOB nan nan nan
583 YHR166C GLOB nan nan nan
584 YLR102C GLOB nan nan nan
585 YKL022C GLOB nan nan nan
586 YNL172W GLOB nan nan nan
587 YLR127C GLOB nan nan nan
588 YDL008W GLOB nan nan nan
589 YOR249C GLOB nan nan nan
590 YBL082C TM nan nan nan
591 YDR135C TM nan nan nan
592 YGL003C GLOB nan nan nan
593 YJL053W GLOB 4.73 0.18 0.04
594 YJL154C GLOB 2.87 0.0 0.0
595 YBL085W GLOB 2.08 0.17 0.08
596 YIR006C GLOB 2.55 0.08 0.03
597 YOL070C GLOB 1.78 0.11 0.06
598 YDR208W GLOB 1.05 0.0 0.0
599 YBL066C GLOB 1.67 0.04 0.02
600 YHR097C GLOB 3.91 0.2 0.05
601 YGR237C GLOB 6.36 2.22 0.35
602 YJR019C GLOB nan nan nan
603 YIL154C GLOB 5.37 1.41 0.26
604 YPR115W GLOB nan nan nan
605 YGR280C GLOB 0.82 0.09 0.11
606 YBL086C GLOB 3.93 0.43 0.11
607 YIL002C GLOB 2.9 0.7 0.24
608 YJL084C GLOB nan nan nan
609 YKR092C GLOB 1.15 0.03 0.02
610 YKL193C GLOB 3.79 0.06 0.02
611 YMR269W GLOB 1.11 0.1 0.09
612 YDR389W GLOB 1.78 0.15 0.08
613 YDR348C GLOB 1.92 0.15 0.08
614 YLR425W GLOB nan nan nan
615 YGR068C GLOB nan nan nan
616 YMR273C GLOB 3.29 0.21 0.06
617 YMR070W GLOB 1.7 0.09 0.05
618 YDR475C GLOB nan nan nan
619 YDR040C TM nan nan nan
620 YGR024C GLOB nan nan nan
621 YGL229C GLOB nan nan nan
622 YDR452W TM 3.56 0.19 0.05
623 YNR002C TM nan nan nan
624 YLR454W GLOB 3.74 0.43 0.12
625 YNR008W TM nan nan nan
626 YPR117W TM nan nan nan
627 YBL087C GLOB nan nan nan
628 YKL021C GLOB 1.17 0.05 0.04
629 YDR361C GLOB 1.22 0.01 0.01
630 YPL208W GLOB 2.67 0.01 0.0
631 YAL025C GLOB 0.87 0.03 0.04
632 YKL082C GLOB 1.06 0.0 0.0
633 YHR088W GLOB 0.76 0.04 0.06
634 YLL008W GLOB 0.97 0.04 0.04
635 YKR081C GLOB 0.95 0.04 0.04
636 YLR276C GLOB 1.25 0.09 0.07
637 YLR009W GLOB 0.88 0.03 0.04
638 YNL061W GLOB 1.07 0.01 0.01
639 YMR049C GLOB 1.04 0.02 0.02
640 YOR294W GLOB 0.98 0.03 0.03
641 YOR272W GLOB 1.05 0.02 0.02
642 YPL093W GLOB 0.83 0.01 0.01
643 YPR143W GLOB 1.11 0.02 0.02

In [ ]:
for index, row in df.iterrows():
    print(index, row["node"], row["DeepTMHMM_class"], row["Christiano_degradation_rate(min-1)"], row["Christiano_degradation_R2"], row["Christiano_halflife_min"])

In [99]:
df = pd.read_pickle("../9-protein-expression/processed-data/0-s288c-step9.pkl")

In [100]:
list(df.columns)

['node',
 '_wkshell',
 'degree_centrality',
 'betweenness_centrality',
 'eigenvector_centrality',
 'closeness_centrality',
 'load_centrality',
 'pagerank',
 'information_centrality',
 'CentralityCosDist_rank',
 'CentralityCosDist_similarity_score',
 'has_verified_sequence',
 'sequence',
 'UniProtKB-AC',
 'DeepTMHMM_trimmed_sequence',
 'DeepTMHMM_class',
 'cleavage_site_start',
 'signalP_trimmed_sequence',
 'ProteinName',
 'GO_terms',
 'GO_terms_human_readable',
 'localization_keywords',
 'parsed_functions',
 'parsed_PTMs',
 'ptm_bronze',
 'ptm_gold',
 'ptm_silver',
 'IDR_count',
 'IDR_sequences',
 'IDR_ranges',
 'N_aa_disordered',
 'disorder_fraction',
 'is_disordered_0.05',
 'is_disordered_0.10',
 'is_disordered_0.15',
 'is_disordered_0.20',
 'is_disordered_0.25',
 'is_disordered_0.30',
 'is_disordered_0.35',
 'is_disordered_0.40',
 'is_disordered_0.45',
 'is_disordered_0.50',
 'is_disordered_0.55',
 'is_disordered_0.60',
 'is_disordered_0.65',
 'is_disordered_0.70',
 'is_disordered_0.75',
 'is_disordered_0.80',
 'is_disordered_0.85',
 'is_disordered_0.90',
 'is_disordered_0.95',
 'is_disordered_1.00',
 'albatross',
 'cider',
 'structure_path',
 'structure_exists',
 'structure_fasta_path',
 'structure_sequence',
 'cleaved_structure_path',
 'cleaved_structure_sequence',
 'sequence_matches_structure',
 'final_structure_path',
 'final_sequence',
 'final_structure_source',
 'mean_plddt',
 'L',
 'dH',
 'dCp',
 'dS',
 'Ghosh-Dill-dG',
 'cagiada-dG',
 'Rosetta_total_score_0001',
 'Rosetta_total_score_0002',
 'Rosetta_total_score_0003',
 'Rosetta_total_score_0004',
 'Rosetta_total_score_0005',
 'Rosetta_total_score_0006',
 'Rosetta_total_score_0007',
 'Rosetta_total_score_0008',
 'Rosetta_total_score_0009',
 'Rosetta_total_score_0010',
 'Rosetta_best_total_score',
 'Rosetta_best_pose_index',
 'Rosetta_best_score_file',
 'Rosetta_n_found',
 'FoldX_total_energy_0001',
 'FoldX_total_energy_0002',
 'FoldX_total_energy_0003',
 'FoldX_total_energy_0004',
 'FoldX_total_energy_0005',
 'FoldX_total_energy_0006',
 'FoldX_total_energy_0007',
 'FoldX_total_energy_0008',
 'FoldX_total_energy_0009',
 'FoldX_total_energy_0010',
 'FoldX_best_total_energy',
 'FoldX_best_pose_index',
 'FoldX_best_file',
 'FoldX_n_found',
 'Christiano_degradation_rate(min-1)',
 'Christiano_degradation_R2',
 'Christiano_halflife_min',
 'Villen_halflife_hours',
 'Villen_halflife_SD_hours',
 'Villen_halflife_CV',
 'Villen_halflife_min',
 'Villen_halflife_SD_min',
 'mean_molecules_per_cell',
 'median_molecules_per_cell',
 'expression_CV']

In [102]:
for index, row in df.iterrows():
    print(index, row["node"], row["mean_molecules_per_cell"], row["median_molecules_per_cell"], row["expression_CV"])

0 YKL063C 2891.0 2223.0 81.0
1 YDL223C 9055.0 5310.0 91.0
2 YPL036W 58400.0 40689.0 73.0
3 YPL050C 5964.0 4596.0 68.0
4 YJR148W 19969.0 15613.0 89.0
5 YHR208W 48648.0 39628.0 70.0
6 YBR035C 25916.0 14922.0 118.0
7 YPR008W 2040.0 1845.0 103.0
8 YKL024C 10435.0 7008.0 63.0
9 YBR286W 19333.0 20329.0 52.0
10 YLR420W 12606.0 11684.0 58.0
11 YKR066C 9350.0 7620.0 81.0
12 YNL117W 7851.0 8647.0 87.0
13 YNL015W 17221.0 14365.0 62.0
14 YOR285W 18914.0 13993.0 87.0
15 YOR239W 9563.0 9715.0 31.0
16 YJL055W 8604.0 6507.0 54.0
17 YJL066C 6399.0 3418.0 110.0
18 YGR027W-A;YGR038C-A;YJR026W;YLR227W-A;YML040W nan nan nan
19 YGL087C 9970.0 4707.0 127.0
20 YNL134C 19782.0 18473.0 53.0
21 YNR034W-A 19224.0 12325.0 93.0
22 YPL111W 35277.0 18625.0 158.0
23 YIR037W 15848.0 10641.0 106.0
24 YML022W 17179.0 14278.0 86.0
25 YNL104C 19271.0 13156.0 75.0
26 YEL060C 52920.0 8037.0 336.0
27 YOR168W 20443.0 18548.0 52.0
28 YER175C 6966.0 6073.0 89.0
29 YEL071W 28560.0 24138.0 63.0
30 YBR222C 6683.0 6256.0 48.0
31 YOR323C 14298.0 9049.0 77.0
32 YBL037W 2255.0 2047.0 74.0
33 YOL062C 1781.0 1935.0 63.0
34 YJR005W 2005.0 2237.0 49.0
35 YLR352W 518.0 322.0 82.0
36 YNL059C 4041.0 3202.0 57.0
37 YBL024W 14613.0 14175.0 42.0
38 YDR356W 3268.0 3057.0 72.0
39 YBR149W 19038.0 14493.0 84.0
40 YDR037W 34618.0 34286.0 48.0
41 YLR421C 10983.0 6873.0 123.0
42 YFL048C 6683.0 6864.0 50.0
43 YDR270W 935.0 1155.0 81.0
44 YKL042W 2440.0 2464.0 39.0
45 YHR019C 36180.0 36081.0 47.0
46 YLL018C 37832.0 33156.0 84.0
47 YKL103C 9685.0 8293.0 61.0
48 YLR080W 1861.0 1818.0 57.0
49 YLR072W 1439.0 1118.0 78.0
50 YNL225C 1884.0 1901.0 52.0
51 YLR250W 6525.0 5115.0 76.0
52 YOL158C 677.0 176.0 154.0
53 YNL231C 11458.0 12084.0 35.0
54 YOR373W 1573.0 1638.0 54.0
55 YPL124W 1874.0 1475.0 86.0
56 YDL201W 5175.0 4535.0 44.0
57 YDL195W 18322.0 19566.0 47.0
58 YDR091C 16307.0 16040.0 44.0
59 YEL034W 120007.0 50245.0 90.0
60 YDR388W 18723.0 10054.0 197.0
61 YER007C-A 11488.0 8015.0 63.0
62 YEL065W 2354.0 2822.0 74.0
63 YER178W 27471.0 19844.0 88.0
64 YER048C 12235.0 12469.0 44.0
65 YGL245W 44909.0 38110.0 48.0
66 YFR009W 14442.0 13923.0 29.0
67 YHR020W 30097.0 31079.0 40.0
68 YJR014W 10198.0 8741.0 42.0
69 YNL247W 14111.0 9429.0 63.0
70 YLR244C 15176.0 14218.0 52.0
71 YOL111C 13135.0 10397.0 68.0
72 YOR187W 19767.0 14557.0 121.0
73 YPL048W 31617.0 23200.0 81.0
74 YPR163C 23913.0 24565.0 40.0
75 YDR406W 3345.0 2838.0 74.0
76 YMR058W 11340.0 5727.0 91.0
77 YPR154W 6153.0 4075.0 86.0
78 YGR185C 29056.0 28107.0 46.0
79 YDL182W 40927.0 21258.0 115.0
80 YGR054W 13708.0 14358.0 54.0
81 YGR285C 46132.0 46597.0 52.0
82 YHR064C 53216.0 41718.0 67.0
83 YJR047C 24129.0 7323.0 204.0
84 YIL078W 29317.0 29362.0 38.0
85 YPL160W 52163.0 49749.0 60.0
86 YPR033C 17824.0 18532.0 36.0
87 YCL001W 3661.0 2957.0 57.0
88 YDL072C 8802.0 8579.0 37.0
89 YDL015C 9036.0 7707.0 58.0
90 YDR144C 2436.0 1153.0 106.0
91 YDR245W 4257.0 3189.0 66.0
92 YEL036C 3933.0 3411.0 62.0
93 YGL105W 36377.0 38196.0 30.0
94 YFR024C-A 9194.0 6043.0 91.0
95 YJL171C 7206.0 4773.0 98.0
96 YGL200C 11208.0 10421.0 51.0
97 YKL065C 7581.0 7431.0 31.0
98 YKL165C 4895.0 2637.0 210.0
99 YLR386W 3294.0 2539.0 86.0
100 YML115C 3719.0 3403.0 51.0
101 YML067C 4191.0 4043.0 34.0
102 YNL121C 18134.0 14978.0 67.0
103 YMR008C 3245.0 2653.0 60.0
104 YOR153W 14232.0 10371.0 90.0
105 YOR016C 4520.0 4267.0 49.0
106 YGR094W 37502.0 39560.0 47.0
107 YJL080C 36064.0 34834.0 61.0
108 YKL081W 73592.0 69914.0 61.0
109 YBR025C 42069.0 38234.0 25.0
110 YLR109W 354824.0 291203.0 105.0
111 YOL082W 977.0 1152.0 44.0
112 YGL156W 3325.0 2113.0 98.0
113 YAL042W 6376.0 5095.0 51.0
114 YAL007C 8087.0 6821.0 66.0
115 YBR187W 2246.0 1978.0 84.0
116 YAR002C-A 9892.0 9253.0 44.0
117 YGL167C 7592.0 7303.0 58.0
118 YBR205W 4140.0 2373.0 75.0
119 YHR034C 2840.0 2835.0 42.0
120 YMR038C 13487.0 11594.0 65.0
121 YNL208W 110728.0 22792.0 238.0
122 YBR096W 4066.0 4586.0 45.0
123 YGL125W 6669.0 6485.0 48.0
124 YBR145W 8233.0 5578.0 81.0
125 YJR109C 70082.0 27875.0 166.0
126 YGL140C 1659.0 1831.0 46.0
127 YOR222W 27568.0 9909.0 199.0
128 YLR216C 24632.0 26863.0 47.0
129 YMR260C 23331.0 21045.0 60.0
130 YPR080W 783350.0 533920.0 156.0
131 YLR247C 800.0 558.0 85.0
132 YDR172W 28454.0 26399.0 67.0
133 YJL001W 17244.0 15579.0 57.0
134 YER094C 14223.0 15457.0 85.0
135 YPR131C 2370.0 1865.0 62.0
136 YHL034C 28066.0 25752.0 49.0
137 YJL063C 4301.0 3555.0 55.0
138 YDR237W 3329.0 3880.0 37.0
139 YJR145C;YHR203C nan nan nan
140 YJL096W 4645.0 3447.0 88.0
141 YKL170W 6798.0 5069.0 85.0
142 YKL138C 2731.0 2522.0 52.0
143 YKR085C 3953.0 3181.0 96.0
144 YKR006C 4463.0 5003.0 54.0
145 YML009C 3309.0 2555.0 85.0
146 YLR196W 13166.0 12030.0 69.0
147 YMR024W 5402.0 5017.0 57.0
148 YML025C 4769.0 3628.0 113.0
149 YNL005C 4298.0 4855.0 42.0
150 YMR286W 3551.0 3405.0 49.0
151 YNL252C 5228.0 5114.0 63.0
152 YNL177C 3597.0 3277.0 67.0
153 YNR022C 4091.0 3934.0 46.0
154 YNL284C 3870.0 4056.0 53.0
155 YOR017W 1710.0 1451.0 85.0
156 YOL041C 7772.0 7150.0 46.0
157 YPL173W 4345.0 4845.0 70.0
158 YOR150W 3845.0 3609.0 58.0
159 YER165W 71808.0 62422.0 65.0
160 YGL049C 7702.0 7053.0 51.0
161 YGR162W 19492.0 21078.0 57.0
162 YGL094C 2628.0 1449.0 134.0
163 YJL186W 6744.0 4859.0 52.0
164 YJL002C 10421.0 10487.0 49.0
165 YMR193W 3592.0 3176.0 58.0
166 YKL025C 2696.0 2837.0 46.0
167 YGR076C 2758.0 2403.0 51.0
168 YGL068W 12895.0 9181.0 97.0
169 YGR220C 2740.0 3043.0 64.0
170 YMR098C 1360.0 1522.0 50.0
171 YNL185C 5566.0 3873.0 75.0
172 YBR082C 18037.0 14172.0 83.0
173 YDR214W 16602.0 13820.0 74.0
174 YCR093W 6369.0 6644.0 47.0
175 YER168C 5477.0 4481.0 53.0
176 YER068W 4800.0 4967.0 30.0
177 YMR235C 22564.0 18167.0 48.0
178 YKL010C 3564.0 3065.0 46.0
179 YKR059W 87284.0 52628.0 102.0
180 YJL138C 97086.0 92322.0 52.0
181 YDL084W 29504.0 29329.0 46.0
182 YDL140C 16726.0 16113.0 66.0
183 YOR046C 12877.0 11463.0 48.0
184 YKL190W 5487.0 4890.0 60.0
185 YBR022W 2955.0 1827.0 85.0
186 YBR017C 5100.0 4755.0 59.0
187 YBR080C 8300.0 6685.0 53.0
188 YBR214W 7441.0 5164.0 92.0
189 YBR143C 34317.0 36685.0 36.0
190 YDL160C 14401.0 12762.0 62.0
191 YDL022W 35400.0 26223.0 82.0
192 YDL192W 39546.0 33643.0 70.0
193 YDR408C 8179.0 7420.0 53.0
194 YDR341C 25403.0 26491.0 61.0
195 YER086W 15941.0 12010.0 100.0
196 YGR173W 8725.0 8578.0 35.0
197 YFL037W 21334.0 18960.0 60.0
198 YHL011C 14233.0 10069.0 92.0
199 YGR175C 25839.0 16391.0 82.0
200 YIL094C 14344.0 12211.0 56.0
201 YKL196C 15308.0 15528.0 41.0
202 YJR072C 6713.0 5354.0 46.0
203 YKR080W 13857.0 12619.0 51.0
204 YLR113W 8225.0 7457.0 42.0
205 YLL026W 54737.0 35086.0 104.0
206 YLR270W 13076.0 11214.0 95.0
207 YLR180W 69028.0 65133.0 54.0
208 YMR186W 218787.0 134828.0 129.0
209 YNL129W 2774.0 2517.0 59.0
210 YNL016W 25274.0 22861.0 55.0
211 YPL010W 11409.0 7856.0 94.0
212 YNL307C 11239.0 8487.0 68.0
213 YPL240C 117582.0 86723.0 127.0
214 YPL218W 67636.0 21432.0 181.0
215 YOL142W 4242.0 4545.0 33.0
216 YHR103W 2016.0 1823.0 62.0
217 YER073W 20347.0 19764.0 73.0
218 YJR024C 5125.0 4007.0 86.0
219 YLR089C 8635.0 8369.0 33.0
220 YKL120W 10498.0 9000.0 79.0
221 YMR108W 37533.0 32177.0 128.0
222 YOL096C 1118.0 1264.0 48.0
223 YOR136W 26753.0 18982.0 122.0
224 YKL126W 5954.0 6096.0 44.0
225 YNL064C 50310.0 41251.0 61.0
226 YPL225W 21308.0 12973.0 128.0
227 YDL190C 4680.0 4158.0 45.0
228 YEL022W 4103.0 3973.0 46.0
229 YDR129C 24543.0 25994.0 44.0
230 YGR218W 9653.0 8276.0 56.0
231 YIL156W-B 10793.0 6503.0 110.0
232 YLR268W 6359.0 4602.0 101.0
233 YJR077C 42578.0 15673.0 228.0
234 YMR145C 12632.0 9235.0 91.0
235 YOR075W 2090.0 1797.0 73.0
236 YPL063W 8426.0 7101.0 62.0
237 YBR122C 2874.0 2713.0 43.0
238 YBL038W 2182.0 2185.0 48.0
239 YDR041W 3922.0 3852.0 64.0
240 YCR071C 3570.0 2797.0 85.0
241 YDR116C 4080.0 3737.0 55.0
242 YDR322W 4463.0 3928.0 58.0
243 YDR296W 4636.0 4490.0 42.0
244 YEL050C 3558.0 1614.0 187.0
245 YDR462W 3563.0 3243.0 45.0
246 YLR312W-A 5193.0 4427.0 75.0
247 YNL047C 1184.0 873.0 83.0
248 YNR039C 1968.0 1991.0 78.0
249 YFR033C 6277.0 5867.0 52.0
250 Q0250 4243.0 4586.0 71.0
251 YLR298C 2215.0 1777.0 75.0
252 YGL191W 5490.0 4547.0 70.0
253 YGL187C 35366.0 9410.0 251.0
254 YHR001W-A 4683.0 4284.0 57.0
255 YGR132C 19346.0 9836.0 158.0
256 YIL111W 4736.0 3173.0 85.0
257 YHR051W 17741.0 10058.0 143.0
258 YKR016W 10648.0 9782.0 60.0
259 YJL166W 4847.0 4274.0 48.0
260 YLR356W 2377.0 2259.0 42.0
261 YLR038C 13824.0 5348.0 198.0
262 YNL052W 6150.0 3670.0 113.0
263 YMR089C 5097.0 4411.0 51.0
264 YNR018W 4800.0 3444.0 70.0
265 YNL055C 70179.0 21873.0 201.0
266 YPR191W 50371.0 19457.0 275.0
267 YOR065W 7559.0 5162.0 116.0
268 YDR529C 33963.0 13267.0 235.0
269 YCL057C-A 3440.0 2946.0 75.0
270 YEL024W 13650.0 7801.0 156.0
271 YDL067C 12895.0 6217.0 101.0
272 YGR012W 4049.0 4318.0 53.0
273 YGR231C 8508.0 5993.0 92.0
274 YHR003C 3979.0 3419.0 83.0
275 YJL207C 2906.0 2629.0 85.0
276 YMR203W 18239.0 14871.0 106.0
277 YER017C 3473.0 3141.0 66.0
278 YBL030C 36450.0 29722.0 61.0
279 YPL078C 28330.0 20801.0 153.0
280 YKL016C 18666.0 10847.0 180.0
281 Q0045 2325.0 2440.0 69.0
282 YOR271C 7272.0 6426.0 71.0
283 YBR039W 17967.0 18490.0 43.0
284 Q0085 1077.0 1077.0 nan
285 YDL004W 29038.0 11900.0 172.0
286 YDR298C 38834.0 24239.0 207.0
287 YDL181W 11902.0 4583.0 196.0
288 YDR322C-A 8209.0 4762.0 108.0
289 YFR011C 6990.0 4663.0 75.0
290 YJR121W 110916.0 35594.0 270.0
291 YKR049C 6795.0 2775.0 170.0
292 YLR295C 16901.0 16282.0 78.0
293 YML081C-A 9036.0 5122.0 167.0
294 YMR003W 2169.0 1940.0 24.0
295 YNL131W 18989.0 14975.0 86.0
296 YOL077W-A 5308.0 3710.0 107.0
297 YPR020W 7686.0 4748.0 82.0
298 YPL271W 23524.0 14543.0 127.0
299 YDL174C 9348.0 7164.0 84.0
300 YHR079C 716.0 267.0 97.0
301 YIL077C 1846.0 1798.0 53.0
302 YLR090W 2089.0 1886.0 59.0
303 YAL010C 1756.0 1279.0 93.0
304 YER154W 5702.0 5197.0 60.0
305 YKL027W 5136.0 4922.0 39.0
306 YDR430C 5214.0 4862.0 59.0
307 YHR147C 4131.0 3688.0 82.0
308 YGR207C 13151.0 7540.0 108.0
309 YJR080C 3273.0 3669.0 29.0
310 YJR045C 55533.0 54905.0 34.0
311 YLR355C 229408.0 99907.0 145.0
312 YMR083W 21166.0 13761.0 93.0
313 YOR125C 3047.0 2298.0 102.0
314 YMR241W 13648.0 13593.0 40.0
315 YLR259C 76659.0 50754.0 110.0
316 YCL044C 2429.0 2779.0 52.0
317 YGL153W 4145.0 3407.0 65.0
318 YKL148C 10165.0 9672.0 61.0
319 YIL125W 16790.0 11221.0 139.0
320 YLL041C 13215.0 5512.0 214.0
321 YPL132W 1902.0 1702.0 73.0
322 YDR075W 1673.0 1731.0 56.0
323 YNL201C 3038.0 2809.0 50.0
324 YOR390W;YPL279C nan nan nan
325 YBL046W 2528.0 2455.0 49.0
326 YBL047C 12780.0 12983.0 51.0
327 YCR030C 6991.0 6937.0 52.0
328 YHR047C 14898.0 10958.0 117.0
329 YBL051C 4795.0 4817.0 50.0
330 YLR064W 4543.0 4629.0 78.0
331 YBL055C 3140.0 2996.0 51.0
332 YMR198W 979.0 1091.0 82.0
333 YDR207C 1122.0 1199.0 69.0
334 YNL007C 29145.0 28050.0 49.0
335 YPR018W 2783.0 3290.0 66.0
336 YNL091W 2003.0 2300.0 67.0
337 YBL056W 7735.0 7522.0 53.0
338 YGL210W 4583.0 4023.0 51.0
339 YDR071C 27378.0 20526.0 143.0
340 YGR205W 6882.0 4577.0 93.0
341 YBL057C 3894.0 3970.0 52.0
342 YDL126C 34690.0 29012.0 54.0
343 YBR273C 3635.0 3378.0 52.0
344 YBR179C 1780.0 1772.0 44.0
345 YDL091C 1375.0 1356.0 96.0
346 YBR280C 1906.0 1415.0 101.0
347 YDR049W 2832.0 3086.0 45.0
348 YDL132W 4706.0 3627.0 67.0
349 YDR328C 8069.0 5623.0 74.0
350 YDR057W 1507.0 1153.0 69.0
351 YER065C 7645.0 899.0 193.0
352 YDR330W 3436.0 2492.0 62.0
353 YFL044C 3095.0 2682.0 61.0
354 YER100W 3863.0 2708.0 80.0
355 YGR048W 4367.0 3773.0 46.0
356 YIL030C 2736.0 2480.0 57.0
357 YGR119C 7711.0 7048.0 44.0
358 YJR092W 1773.0 1600.0 77.0
359 YJR090C 1579.0 780.0 117.0
360 YLL039C;YLR167W nan nan nan
361 YKL100C 3437.0 3553.0 46.0
362 YLR207W 1614.0 1891.0 52.0
363 YLR088W 1963.0 1932.0 54.0
364 YML029W 2164.0 1822.0 82.0
365 YML013W 3712.0 3056.0 69.0
366 YMR067C 3737.0 3630.0 48.0
367 YML088W 777.0 702.0 64.0
368 YMR119W 718.0 411.0 95.0
369 YNL141W 8618.0 7949.0 59.0
370 YNL085W 4898.0 4097.0 76.0
371 YOR375C 88449.0 55615.0 92.0
372 YOL013C 1435.0 1519.0 64.0
373 YOR157C 15719.0 11679.0 66.0
374 YBL058W 8539.0 6482.0 66.0
375 YBR170C 6257.0 4566.0 99.0
376 YBR056W 12317.0 6076.0 181.0
377 YHR132W-A 6731.0 3781.0 182.0
378 YOR048C 4248.0 3466.0 55.0
379 YBL059C-A 2487.0 1830.0 58.0
380 YBL063W 1624.0 910.0 121.0
381 YBL036C 8255.0 5112.0 67.0
382 YDR036C 4107.0 4212.0 39.0
383 YER136W 16754.0 14010.0 57.0
384 YDR304C 12524.0 11621.0 67.0
385 YBL060W 798.0 755.0 63.0
386 YBL064C 11108.0 8062.0 85.0
387 YPL059W 10894.0 4976.0 140.0
388 YJR016C 53322.0 41540.0 74.0
389 YOR108W 11734.0 8863.0 71.0
390 YER080W 9291.0 7830.0 69.0
391 YER170W 1257.0 1165.0 49.0
392 YML107C 1406.0 1357.0 52.0
393 YAL044W-A 5193.0 3455.0 89.0
394 YGR244C 13468.0 13149.0 57.0
395 YAL046C 3597.0 1951.0 114.0
396 YDR148C 14656.0 6516.0 187.0
397 YGR193C 8543.0 8067.0 72.0
398 YHL021C 13469.0 8617.0 112.0
399 YKL085W 47019.0 20985.0 244.0
400 YLR304C 73663.0 43808.0 125.0
401 YNL071W 16487.0 6585.0 102.0
402 YOR232W 18052.0 10216.0 191.0
403 YPR004C 9993.0 10440.0 37.0
404 YBL068W 8482.0 6454.0 79.0
405 YOL061W 9113.0 9265.0 47.0
406 YBL067C 1826.0 1759.0 79.0
407 YBL071W-A 8705.0 8955.0 41.0
408 YAL020C 810.0 998.0 67.0
409 YGR200C 5742.0 5451.0 36.0
410 YER055C 33658.0 23238.0 86.0
411 YKL110C 3888.0 3020.0 53.0
412 YIL103W 3138.0 2676.0 52.0
413 YLR384C 7597.0 7200.0 34.0
414 YKL191W 3956.0 3129.0 80.0
415 YPL086C 4610.0 4751.0 35.0
416 YBL072C 92966.0 67865.0 108.0
417 YBR084W 9390.0 6654.0 78.0
418 YBL072C;YER102W nan nan nan
419 YCR031C 68874.0 51361.0 81.0
420 YBR189W 139551.0 70257.0 110.0
421 YDL040C 9499.0 8398.0 66.0
422 YCR047C 4329.0 4050.0 65.0
423 YDR025W;YBR048W nan nan nan
424 YDL060W 4563.0 4912.0 44.0
425 YDR117C 5044.0 5374.0 62.0
426 YDR064W 118213.0 62207.0 135.0
427 YER074W;YIL069C nan nan nan
428 YDR450W;YML026C nan nan nan
429 YGR027C 82159.0 59656.0 97.0
430 YGL123W 152569.0 58722.0 132.0
431 YGR214W 115556.0 13774.0 247.0
432 YGR118W;YPR132W nan nan nan
433 YHL015W 119955.0 72189.0 87.0
434 YHL013C 5157.0 3598.0 131.0
435 YJL136C 103726.0 99708.0 81.0
436 YHR013C 7713.0 5599.0 73.0
437 YJR123W 123614.0 46502.0 158.0
438 YJL190C;YLR367W nan nan nan
439 YKL156W;YHR021C nan nan nan
440 YLR048W 144554.0 88691.0 120.0
441 YKR057W 80035.0 66467.0 106.0
442 YLR287C-A;YOR182C nan nan nan
443 YLR150W 78258.0 70456.0 55.0
444 YLR419W 5203.0 4875.0 76.0
445 YLR388W 18070.0 11265.0 93.0
446 YML024W;YDR447C nan nan nan
447 YLR441C 88137.0 50202.0 113.0
448 YMR116C 155688.0 103354.0 107.0
449 YML063W 92875.0 107000.0 70.0
450 YMR143W;YDL083C nan nan nan
451 YNL112W 25092.0 21619.0 50.0
452 YNL096C 64051.0 54294.0 66.0
453 YNL207W 4799.0 4165.0 45.0
454 YNL178W 102188.0 77234.0 95.0
455 YOL040C 94004.0 52121.0 113.0
456 YNL302C 73146.0 48680.0 89.0
457 YOR096W 202553.0 70601.0 132.0
458 YOL121C 58515.0 28109.0 105.0
459 YOR198C 31781.0 33400.0 41.0
460 YOR119C 2557.0 2350.0 54.0
461 YPL090C;YBR181C nan nan nan
462 YOR369C 92317.0 65711.0 97.0
463 YOR133W 72076.0 52464.0 94.0
464 YKR038C 3353.0 3573.0 45.0
465 YDL075W 162099.0 54812.0 158.0
466 YJL191W 34274.0 13149.0 109.0
467 YIL161W 2249.0 2246.0 49.0
468 YLR260W 1326.0 1235.0 50.0
469 YNL073W 1862.0 1987.0 51.0
470 YNL023C 1132.0 1091.0 68.0
471 YOR253W 7671.0 5530.0 103.0
472 YER131W 193309.0 77439.0 208.0
473 YKL032C 4186.0 3621.0 74.0
474 YLR264W 55857.0 8600.0 173.0
475 YNL050C 3824.0 3569.0 48.0
476 YOL080C 3110.0 3192.0 47.0
477 YPL032C 7869.0 4216.0 118.0
478 YDL061C 36364.0 31924.0 76.0
479 YPL081W 81060.0 66820.0 98.0
480 YKL143W 4181.0 3907.0 48.0
481 YNR046W 10193.0 9721.0 67.0
482 YNL224C 1868.0 1832.0 53.0
483 YGR081C 4639.0 4726.0 33.0
484 YLR398C 4623.0 4408.0 43.0
485 YNL314W 1490.0 1148.0 110.0
486 YPL204W 5874.0 5798.0 51.0
487 YPL012W 7241.0 8407.0 51.0
488 YGL189C 181592.0 90556.0 209.0
489 YPL266W 5449.0 3257.0 71.0
490 YNR051C 7525.0 7140.0 48.0
491 YLR327C 5895.0 4867.0 86.0
492 YNL054W-B nan nan nan
493 YLR325C 70481.0 32579.0 172.0
494 YOR359W 3288.0 3371.0 44.0
495 YAL035W 27948.0 25419.0 66.0
496 YAL036C 8769.0 8422.0 40.0
497 YBR263W 13650.0 12340.0 67.0
498 YDL053C 5625.0 4469.0 87.0
499 YDL051W 9417.0 8346.0 43.0
500 YDL213C 5963.0 5221.0 50.0
501 YDR381W 63497.0 26822.0 126.0
502 YDR412W 3792.0 3184.0 56.0
503 YER176W 3128.0 2507.0 98.0
504 YGL205W 2489.0 2489.0 48.0
505 YHL038C 1715.0 1814.0 49.0
506 YIL148W;YKR094C nan nan nan
507 YIL127C 3295.0 3538.0 87.0
508 YKL122C 7044.0 4248.0 168.0
509 YLR061W 165101.0 118983.0 99.0
510 YLR278C 1010.0 1069.0 51.0
511 YOR091W 5808.0 5032.0 52.0
512 YOR293W;YMR230W nan nan nan
513 YPL127C 7992.0 8125.0 46.0
514 YPL123C 2014.0 2047.0 64.0
515 YPL210C 6604.0 6363.0 42.0
516 YIL061C 1711.0 1637.0 65.0
517 YDR266C 3445.0 3143.0 41.0
518 YPL037C 58771.0 46777.0 72.0
519 YBL075C 8507.0 6440.0 150.0
520 YML078W 29839.0 17217.0 131.0
521 YBL074C 1834.0 1034.0 134.0
522 YKL173W 3118.0 3148.0 57.0
523 YHR165C 2115.0 1905.0 62.0
524 YKR018C 6227.0 5866.0 45.0
525 YLR347C 16096.0 15792.0 66.0
526 YBL076C 47281.0 41712.0 49.0
527 YDR035W 17084.0 14267.0 69.0
528 YHR087W 43673.0 17917.0 153.0
529 YNL137C 4479.0 3915.0 67.0
530 YDR050C 364775.0 121824.0 188.0
531 YBR196C 178027.0 158738.0 68.0
532 YPR074C 96705.0 73106.0 85.0
533 YFR053C 81363.0 40800.0 107.0
534 YGL117W 1999.0 1858.0 80.0
535 YBL098W 3370.0 2905.0 75.0
536 YGR138C 2811.0 2938.0 55.0
537 Q0140 4046.0 3940.0 51.0
538 YDR494W 2043.0 2139.0 75.0
539 YBR146W 3973.0 4221.0 56.0
540 YGR150C 1365.0 1300.0 72.0
541 YER050C 2310.0 1870.0 83.0
542 YNL306W 3554.0 3710.0 44.0
543 YMR158W 4277.0 3622.0 70.0
544 YOR158W 4592.0 4581.0 48.0
545 YNR037C 4575.0 3699.0 73.0
546 YPL013C 4089.0 2861.0 80.0
547 YOR205C 1385.0 985.0 137.0
548 YPR166C 1701.0 1756.0 68.0
549 YPL118W 3900.0 3574.0 65.0
550 YNR036C 3635.0 3391.0 98.0
551 YNL292W 5101.0 5553.0 57.0
552 YER105C 3992.0 3875.0 41.0
553 YGL092W 5535.0 5564.0 33.0
554 YFR002W 5860.0 4862.0 62.0
555 YKL057C 2463.0 2270.0 75.0
556 YLR018C 3784.0 4027.0 41.0
557 YKR082W 4984.0 5120.0 42.0
558 YML103C 5127.0 4820.0 56.0
559 YML031W 4871.0 4097.0 124.0
560 YMR153W 4148.0 3648.0 54.0
561 YMR129W 5610.0 5192.0 72.0
562 YHR024C 7423.0 6240.0 85.0
563 YLR163C 5803.0 4095.0 95.0
564 YJL041W 12436.0 10385.0 62.0
565 YBL079W 3411.0 3441.0 41.0
566 YDL116W 4928.0 4730.0 32.0
567 YJL008C 23393.0 23371.0 49.0
568 YAL026C 3602.0 3187.0 64.0
569 YJR042W 4350.0 4095.0 48.0
570 YLR208W 21476.0 17912.0 82.0
571 YPL169C 7114.0 6514.0 44.0
572 YGL172W 5106.0 4241.0 103.0
573 YJL061W 4269.0 4443.0 53.0
574 YBL080C 1666.0 1263.0 81.0
575 YDR061W 3463.0 3422.0 46.0
576 YMR293C 1894.0 1463.0 94.0
577 YBL084C 1689.0 955.0 121.0
578 YDR260C nan nan nan
579 YDR118W 1033.0 1364.0 68.0
580 YGL240W 3441.0 1360.0 142.0
581 YFR036W 2537.0 2537.0 73.0
582 YIR025W 8.0 8.0 nan
583 YHR166C 1049.0 811.0 95.0
584 YLR102C 8076.0 1694.0 143.0
585 YKL022C 3016.0 2073.0 140.0
586 YNL172W 474.0 209.0 121.0
587 YLR127C 519.0 388.0 91.0
588 YDL008W 2007.0 2709.0 75.0
589 YOR249C 621.0 424.0 109.0
590 YBL082C 1693.0 1472.0 74.0
591 YDR135C 4726.0 4264.0 78.0
592 YGL003C 2073.0 632.0 160.0
593 YJL053W 3245.0 2613.0 49.0
594 YJL154C 3728.0 4037.0 33.0
595 YBL085W 3220.0 2526.0 73.0
596 YIR006C 9830.0 9763.0 43.0
597 YOL070C 3287.0 3091.0 56.0
598 YDR208W 1853.0 1925.0 62.0
599 YBL066C 582.0 442.0 78.0
600 YHR097C 4829.0 4009.0 81.0
601 YGR237C 1734.0 1503.0 66.0
602 YJR019C 5186.0 2226.0 128.0
603 YIL154C 2613.0 1972.0 60.0
604 YPR115W 1916.0 1512.0 85.0
605 YGR280C 3876.0 3881.0 42.0
606 YBL086C 1799.0 1567.0 66.0
607 YIL002C 1242.0 1169.0 83.0
608 YJL084C 1813.0 1946.0 62.0
609 YKR092C 9596.0 9434.0 53.0
610 YKL193C 7706.0 5650.0 67.0
611 YMR269W 2985.0 2965.0 46.0
612 YDR389W 2455.0 2368.0 77.0
613 YDR348C 4426.0 3893.0 65.0
614 YLR425W 630.0 509.0 97.0
615 YGR068C 1347.0 1317.0 50.0
616 YMR273C 1267.0 1162.0 82.0
617 YMR070W 2801.0 2570.0 66.0
618 YDR475C 1771.0 1350.0 97.0
619 YDR040C 3059.0 2891.0 68.0
620 YGR024C 2544.0 2451.0 46.0
621 YGL229C 675.0 506.0 86.0
622 YDR452W 3170.0 2626.0 94.0
623 YNR002C nan nan nan
624 YLR454W 2230.0 1620.0 71.0
625 YNR008W 2464.0 2021.0 104.0
626 YPR117W 604.0 437.0 94.0
627 YBL087C 30149.0 12746.0 170.0
628 YKL021C 4911.0 4179.0 52.0
629 YDR361C 7404.0 6452.0 42.0

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3927 entries, 0 to 3926
Columns: 109 entries, node to Median molecules per cell
dtypes: bool(2), float64(49), int64(24), object(34)
memory usage: 3.2+ MB